url: https://www.fema.gov/openfema-data-page/fima-nfip-redacted-claims-v2
name: FEMA NFIP Claims
expected_update_frequency: monthly
tags:
  - fema
  - api
  - nfip
  - flood-insurance
api_config:
  url: https://www.fema.gov/api/open/v2/FimaNfipClaims
  method: GET
  params:
    $top: 1
  expected_fields:
    - metadata.count
    - FimaNfipClaims[0].agricultureStructureIndicator
    - FimaNfipClaims[0].asOfDate
    - FimaNfipClaims[0].basementEnclosureCrawlspaceType
    - FimaNfipClaims[0].policyCount
    - FimaNfipClaims[0].crsClassificationCode
    - FimaNfipClaims[0].dateOfLoss
    - FimaNfipClaims[0].elevatedBuildingIndicator
    - FimaNfipClaims[0].elevationCertificateIndicator
    - FimaNfipClaims[0].elevationDifference
    - FimaNfipClaims[0].baseFloodElevation
    - FimaNfipClaims[0].ratedFloodZone
    - FimaNfipClaims[0].houseWorship
    - FimaNfipClaims[0].locationOfContents
    - FimaNfipClaims[0].lowestAdjacentGrade
    - FimaNfipClaims[0].lowestFloorElevation
    - FimaNfipClaims[0].numberOfFloorsInTheInsuredBuilding
    - FimaNfipClaims[0].nonProfitIndicator
    - FimaNfipClaims[0].obstructionType
    - FimaNfipClaims[0].occupancyType
    - FimaNfipClaims[0].originalConstructionDate
    - FimaNfipClaims[0].originalNBDate
    - FimaNfipClaims[0].amountPaidOnBuildingClaim
    - FimaNfipClaims[0].amountPaidOnContentsClaim
    - FimaNfipClaims[0].amountPaidOnIncreasedCostOfComplianceClaim
    - FimaNfipClaims[0].postFIRMConstructionIndicator
    - FimaNfipClaims[0].rateMethod
    - FimaNfipClaims[0].smallBusinessIndicatorBuilding
    - FimaNfipClaims[0].totalBuildingInsuranceCoverage
    - FimaNfipClaims[0].totalContentsInsuranceCoverage
    - FimaNfipClaims[0].yearOfLoss
    - FimaNfipClaims[0].primaryResidenceIndicator
    - FimaNfipClaims[0].buildingDamageAmount
    - FimaNfipClaims[0].buildingDeductibleCode
    - FimaNfipClaims[0].netBuildingPaymentAmount
    - FimaNfipClaims[0].buildingPropertyValue
    - FimaNfipClaims[0].causeOfDamage
    - FimaNfipClaims[0].condominiumCoverageTypeCode
    - FimaNfipClaims[0].contentsDamageAmount
    - FimaNfipClaims[0].contentsDeductibleCode
    - FimaNfipClaims[0].netContentsPaymentAmount
    - FimaNfipClaims[0].contentsPropertyValue
    - FimaNfipClaims[0].disasterAssistanceCoverageRequired
    - FimaNfipClaims[0].eventDesignationNumber
    - FimaNfipClaims[0].ficoNumber
    - FimaNfipClaims[0].floodCharacteristicsIndicator
    - FimaNfipClaims[0].floodWaterDuration
    - FimaNfipClaims[0].floodproofedIndicator
    - FimaNfipClaims[0].floodEvent
    - FimaNfipClaims[0].iccCoverage
    - FimaNfipClaims[0].netIccPaymentAmount
    - FimaNfipClaims[0].nfipRatedCommunityNumber
    - FimaNfipClaims[0].nfipCommunityNumberCurrent
    - FimaNfipClaims[0].nfipCommunityName
    - FimaNfipClaims[0].nonPaymentReasonContents
    - FimaNfipClaims[0].nonPaymentReasonBuilding
    - FimaNfipClaims[0].numberOfUnits
    - FimaNfipClaims[0].buildingReplacementCost
    - FimaNfipClaims[0].contentsReplacementCost
    - FimaNfipClaims[0].replacementCostBasis
    - FimaNfipClaims[0].stateOwnedIndicator
    - FimaNfipClaims[0].waterDepth
    - FimaNfipClaims[0].floodZoneCurrent
    - FimaNfipClaims[0].buildingDescriptionCode
    - FimaNfipClaims[0].rentalPropertyIndicator
    - FimaNfipClaims[0].state
    - FimaNfipClaims[0].reportedCity
    - FimaNfipClaims[0].reportedZipCode
    - FimaNfipClaims[0].countyCode
    - FimaNfipClaims[0].censusTract
    - FimaNfipClaims[0].censusBlockGroupFips
    - FimaNfipClaims[0].latitude
    - FimaNfipClaims[0].longitude
    - FimaNfipClaims[0].id
