url: https://cdmrp.health.mil/search.aspx
name: Congressionally Directed Medical Research Programs
expected_update_frequency: daily
tags: [health, research]
api_config:
  url: https://cdmrp.health.mil/api/search/awards
  method: GET
  params:
    sort: date_desc
    limit: 1
  expected_fields:
    - total_count
    - awards[0].award_id
    - awards[0].title
    - awards[0].award_amount
    - awards[0].award_date
    - awards[0].institution
    - awards[0].pi_name
    - awards[0].program
  date_field: awards[0].award_date
