url: https://www.fema.gov/openfema-data-page/registration-intake-and-individuals-household-program-ri-ihp-v2
name: FEMA Registration Intake and IHP
expected_update_frequency: daily
tags:
  - fema
  - api
  - individual-assistance
  - disaster-recovery
api_config:
  url: https://www.fema.gov/api/open/v2/RegistrationIntakeIndividualsHouseholdPrograms
  method: GET
  params:
    $top: 1
  expected_fields:
    - metadata.count
    - RegistrationIntakeIndividualsHouseholdPrograms[0].disasterNumber
    - RegistrationIntakeIndividualsHouseholdPrograms[0].state
    - RegistrationIntakeIndividualsHouseholdPrograms[0].county
    - RegistrationIntakeIndividualsHouseholdPrograms[0].city
    - RegistrationIntakeIndividualsHouseholdPrograms[0].zipCode
