url: https://www.fema.gov/openfema-data-page/public-assistance-funded-projects-details-v1
name: FEMA Public Assistance Grant Awards
expected_update_frequency: daily
tags:
  - fema
  - api
  - public-assistance
  - grants
api_config:
  url: https://www.fema.gov/api/open/v1/PublicAssistanceFundedProjectsDetails
  method: GET
  params:
    $top: 1
  date_field: PublicAssistanceFundedProjectsDetails[0].lastRefreshDate
  expected_fields:
    - metadata.count
    - PublicAssistanceFundedProjectsDetails
