url: https://nces.ed.gov/nationsreportcard/about/
name: NCES National Assessment of Educational Progress (NAEP)
expected_update_frequency: quarterly
tags: [education, nces, assessment]
api_config:
  url: https://nces.ed.gov/nationsreportcard/api/v1/assessments
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - assessments[0].year
    - assessments[0].subject
    - assessments[0].grade
    - assessments[0].type
    - assessments[0].status
    - assessments[0].release_date
  date_field: assessments[0].release_date
