url: https://www.fema.gov/openfema-data-page/fima-nfip-redacted-policies-v2
name: FEMA NFIP Policies
expected_update_frequency: monthly
tags:
  - fema
  - api
  - nfip
  - flood-insurance
api_config:
  url: https://www.fema.gov/api/open/v2/FimaNfipPolicies
  method: GET
  params:
    $top: 1
  date_field: FimaNfipPolicies[0].asOfDate
  expected_fields:
    - metadata.count
    - FimaNfipPolicies
linked_urls:
  - url: https://www.fema.gov/about/openfema/faq
    name: OpenFEMA FAQs