url: https://www.fema.gov/openfema-data-page/fima-nfip-redacted-policies-v2
name: FEMA NFIP Policies
expected_update_frequency: monthly
tags:
  - fema
  - api
  - nfip
  - flood-insurance
api_config:
  url: https://www.fema.gov/api/open/v2/FimaNfipPolicies
  method: GET
  params:
    $top: 1
  expected_fields:
    - metadata.count
    - FimaNfipPolicies[0].occupancyType
    - FimaNfipPolicies[0].elevationDifference
    - FimaNfipPolicies[0].totalBuildingInsuranceCoverage
    - FimaNfipPolicies[0].totalContentsInsuranceCoverage
    - FimaNfipPolicies[0].totalInsurancePremiumOfThePolicy
    - FimaNfipPolicies[0].agricultureStructureIndicator
    - FimaNfipPolicies[0].baseFloodElevation
    - FimaNfipPolicies[0].basementEnclosureCrawlspaceType
    - FimaNfipPolicies[0].cancellationDateOfFloodPolicy
    - FimaNfipPolicies[0].condominiumCoverageTypeCode
    - FimaNfipPolicies[0].construction
    - FimaNfipPolicies[0].crsClassCode
    - FimaNfipPolicies[0].buildingDeductibleCode
    - FimaNfipPolicies[0].contentsDeductibleCode
    - FimaNfipPolicies[0].elevatedBuildingIndicator
    - FimaNfipPolicies[0].elevationCertificateIndicator
    - FimaNfipPolicies[0].elevationDifference
    - FimaNfipPolicies[0].federalPolicyFee
linked_urls:
  - https://www.fema.gov/sites/default/files/documents/fema_nfip-data-faqs.pdf
