url: https://nces.ed.gov/surveys/bps/
name: NCES Beginning Postsecondary Students (BPS)
expected_update_frequency: yearly
tags: [education, nces, postsecondary]
api_config:
  url: https://nces.ed.gov/api/bps/cohorts
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - cohorts[0].year
    - cohorts[0].name
    - cohorts[0].description
    - cohorts[0].status
    - cohorts[0].release_date
  date_field: cohorts[0].release_date
