url: https://www.fema.gov/openfema-data-page/hazard-mitigation-plan-statuses-v1
name: FEMA Hazard Mitigation Plan Status
expected_update_frequency: daily
tags:
  - fema
  - api
  - hazard-mitigation
  - planning
api_config:
  url: https://www.fema.gov/api/open/v1/HazardMitigationPlanStatuses
  method: GET
  params:
    $top: 1
  date_field: HazardMitigationPlanStatuses[0].lastRefreshDate
  expected_fields:
    - metadata.count
    - HazardMitigationPlanStatuses
