url: https://nces.ed.gov/surveys/btls/
name: NCES Beginning Teacher Longitudinal Study (BTLS)
expected_update_frequency: yearly
tags: [education, nces, teachers, longitudinal]
api_config:
  url: https://nces.ed.gov/api/btls/waves
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - waves[0].year
    - waves[0].wave_number
    - waves[0].status
    - waves[0].release_date
  date_field: waves[0].release_date
