url: https://ocrdata.ed.gov/
name: Civil Rights Data Collection
expected_update_frequency: yearly
tags: [education, civil-rights, ed]
api_config:
  url: https://ocrdata.ed.gov/api/collections
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - collections[0].year
    - collections[0].name
    - collections[0].status
    - collections[0].release_date
    - collections[0].data_years
    - collections[0].universe_count
  date_field: collections[0].release_date
