url: https://www.fema.gov/openfema-data-page/fema-web-disaster-summaries-v1
name: FEMA Web Disaster Summaries
expected_update_frequency: daily
tags:
  - fema
  - api
  - disaster-summaries
api_config:
  url: https://www.fema.gov/api/open/v1/FemaWebDisasterSummaries
  method: GET
  params:
    $top: 1
  date_field: FemaWebDisasterSummaries[0].lastRefreshDate
  expected_fields:
    - metadata.count
    - FemaWebDisasterSummaries
