url: https://www.fema.gov/openfema-data-page/ipaws-archived-alerts-v1
name: FEMA IPAWS Archived Alerts
expected_update_frequency: daily
tags:
  - fema
  - api
  - ipaws
  - alerts
api_config:
  url: https://www.fema.gov/api/open/v1/IpawsArchivedAlerts
  method: GET
  params:
    $top: 1
  date_field: IpawsArchivedAlerts[0].lastRefreshDate
  expected_fields:
    - metadata.count
    - IpawsArchivedAlerts
