url: https://nces.ed.gov/surveys/frss/
name: Fast Response Survey System (FRSS)
expected_update_frequency: quarterly
tags: [education, nces, survey]
api_config:
  url: https://nces.ed.gov/api/frss/surveys
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - surveys[0].survey_id
    - surveys[0].title
    - surveys[0].year
    - surveys[0].topic
    - surveys[0].status
    - surveys[0].release_date
  date_field: surveys[0].release_date
