url: https://nces.ed.gov/nhes/
name: National Household Education Surveys Program (NHES)
expected_update_frequency: yearly
tags: [education, nces, household, survey]
api_config:
  url: https://nces.ed.gov/api/nhes/collections
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - collections[0].year
    - collections[0].surveys
    - collections[0].status
    - collections[0].release_date
    - collections[0].sample_size
    - collections[0].response_rate
  date_field: collections[0].release_date
