url: https://www.fema.gov/openfema-data-page/emergency-management-performance-grants-v2
name: FEMA Emergency Management Performance Grants
expected_update_frequency: quarterly
tags:
  - fema
  - api
  - grants
  - emergency-management
api_config:
  url: https://www.fema.gov/api/open/v2/EmergencyManagementPerformanceGrants
  method: GET
  params:
    $top: 1
  expected_fields:
    - metadata.count
    - EmergencyManagementPerformanceGrants[0].state
