url: https://nces.ed.gov/surveys/npsas/
name: National Postsecondary Student Aid Study (NPSAS)
expected_update_frequency: yearly
tags: [education, nces, postsecondary, financial-aid]
api_config:
  url: https://nces.ed.gov/api/npsas/studies
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - studies[0].year
    - studies[0].name
    - studies[0].status
    - studies[0].release_date
    - studies[0].sample_size
    - studies[0].institution_count
  date_field: studies[0].release_date
