url: https://nces.ed.gov/surveys/pss/
name: Private School Survey (PSS)
expected_update_frequency: yearly
tags: [education, nces, private-schools]
api_config:
  url: https://nces.ed.gov/api/pss/surveys
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - surveys[0].school_year
    - surveys[0].status
    - surveys[0].release_date
    - surveys[0].school_count
    - surveys[0].student_count
  date_field: surveys[0].release_date
