url: https://nces.ed.gov/surveys/ssocs/
name: School Survey on Crime and Safety (SSOCS)
expected_update_frequency: yearly
tags: [education, nces, safety, crime]
api_config:
  url: https://nces.ed.gov/api/ssocs/surveys
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - surveys[0].school_year
    - surveys[0].status
    - surveys[0].release_date
    - surveys[0].sample_size
    - surveys[0].response_rate
  date_field: surveys[0].release_date
