url: https://fiscaldata.treasury.gov/datasets/treasury-offset-program/
name: Treasury Offset Program
expected_update_frequency: monthly
tags: [treasury, debt-collection]
api_config:
  url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/top
  method: GET
  params:
    sort: -record_date
    page[size]: 1
  expected_fields:
    - meta.count
    - meta.labels
    - data[0].record_date
    - data[0].record_calendar_year
    - data[0].record_fiscal_year
    - data[0].debt_type
    - data[0].debt_type_description
    - data[0].agency_name
    - data[0].state_name
    - data[0].payment_amount
  date_field: data[0].record_date
