url: https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/
name: Debt to the Penny
expected_update_frequency: daily
tags: [treasury, debt]
api_config:
  url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny
  method: GET
  params:
    sort: -record_date
    page[size]: 1
  expected_fields:
    - meta.count
    - meta.labels
    - data[0].record_date
    - data[0].debt_held_public_amt
    - data[0].intragov_hold_amt
    - data[0].tot_pub_debt_out_amt
    - data[0].src_line_nbr
    - data[0].record_fiscal_year
    - data[0].record_fiscal_quarter
    - data[0].record_calendar_year
    - data[0].record_calendar_quarter
    - data[0].record_calendar_month
    - data[0].record_calendar_day
  date_field: data[0].record_date
