url: https://www.cdc.gov/healthyyouth/data/yrbs/index.htm
name: Youth Risk Behavior Surveillance System (YRBSS)
expected_update_frequency: yearly
tags: [health, youth, cdc, survey]
api_config:
  url: https://chronicdata.cdc.gov/resource/q6p7-56au.json
  method: GET
  params:
    $order: year DESC
    $limit: 1
  expected_fields:
    - year
    - locationabbr
    - locationdesc
    - datasource
    - class
    - topic
    - question
    - response
    - sample_size
    - data_value
    - confidence_limit_low
    - confidence_limit_high
    - display_order
  date_field: year
