url: https://mrdc.health.mil
name: U.S. Army Medical Research and Development Command
expected_update_frequency: null
tags:
  - health
  - military
linked_urls:
  - url: http://www.army.mil
    name: [No text]
  - url: https://www.army.mil/futures/
    name: [No text]
  - url: https://cdmrp.health.mil/
    name: CDMRP
  - url: https://www.tatrc.org/
    name: TATRC
  - url: https://usaarl.health.mil/
    name: USAARL
  - url: https://usaisr.health.mil/
    name: USAISR
  - url: https://usammda.health.mil/
    name: USAMMDA
  - url: https://usamraa.health.mil/Pages/Main01.aspx
    name: USAMRAA
  - url: https://usamricd.health.mil/
    name: USAMRICD
  - url: https://usamriid.health.mil/
    name: USAMRIID
  - url: https://usariem.health.mil/
    name: USARIEM
  - url: https://wrair.health.mil/
    name: WRAIR
  - url: https://mrdc.health.mil/index.cfm/about/faqs
    name: FAQs
  - url: https://mrdc.health.mil/index.cfm/contact_us
    name: Contact Us
  - url: https://mrdc.health.mil/index.cfm/sitemap
    name: Sitemap
  - url: https://mrdc.health.mil
    name: About
  - url: https://mrdc.health.mil/index.cfm/about/mission_vision
    name: Mission/Vision
  - url: https://mrdc.health.mil/index.cfm/about/history
    name: Command History
  - url: https://mrdc.health.mil/index.cfm/about/leadership
    name: Leadership
  - url: https://mrdc.health.mil/index.cfm/about/headquarters
    name: MRDC Headquarters
  - url: https://mrdc.health.mil/index.cfm/about/subordinate_commands
    name: Subordinate Commands
  - url: https://mrdc.health.mil/index.cfm/about/inspector_general
    name: Inspector General
  - url: https://mrdc.health.mil/index.cfm/about/jag
    name: Staff Judge Advocate
  - url: https://mrdc.health.mil/index.cfm/program_areas/medical_research_and_development
    name: Medical Research & Development
  - url: https://mrdc.health.mil/index.cfm/program_areas/medical_product_development
    name: Medical Program
  - url: https://mrdc.health.mil/index.cfm/program_areas/medical_materiel
    name: Medical Materiel
  - url: https://mrdc.health.mil/index.cfm/media/articles
    name: Articles
  - url: https://mrdc.health.mil/index.cfm/media/news_releases
    name: News Releases
  - url: https://mrdc.health.mil/index.cfm/media/publications
    name: Strategic Communication Products
  - url: https://www.flickr.com/photos/usamrmc/albums
    name: Images
  - url: https://mrdc.health.mil/index.cfm/media/social_media
    name: Social Media Hub
  - url: https://mrdc.health.mil/index.cfm/collaborate/doing_business_with_us
    name: Doing Business With Us
  - url: https://mrdc.health.mil/index.cfm/collaborate/research_protections
    name: Research Protections
  - url: https://mrdc.health.mil/index.cfm/collaborate/technology_transfer
    name: Technology Transfer
  - url: https://mrdc.health.mil/index.cfm/collaborate/submit_proposal
    name: Submit a Research Proposal
  - url: https://mrdc.health.mil/index.cfm/resources/researcher_resources
    name: Researcher Resources
  - url: https://mrdc.health.mil/index.cfm/resources/employment
    name: Employment
  - url: https://mrdc.health.mil/index.cfm/resources/mrdc_resources
    name: MRDC Resources
  - url: https://mrdc.health.mil/index.cfm/resources/soldier_care
    name: Soldier Care
  - url: https://mrdc.health.mil/index.cfm/resources/links
    name: Links
  - url: https://mrdc.health.mil/index.cfm/resources/educational_opportunities
    name: Educational Opportunities
  - url: https://mrdc.health.mil/index.cfm/media/articles/2025/after_DOD_award_datlof_looks_to_future_of_military_medical_technology_transfer
    name: read full story
  - url: https://mrdc.health.mil/index.cfm/media/articles/2025/USAMRICD_researchers_receive_presidential_science_award
    name: read full story
  - url: https://mrdc.health.mil/index.cfm/media/articles/2025/when_in_doubt_call_USAMRIID_US_army_north_exercise_tests_biological_threat_response
    name: read full story
  - url: https://mrdc.health.mil/index.cfm/media/articles/2025/USAISRs_cancio_named_american_burn_association_president
    name: read full story
  - url: https://mrdc.health.mil/index.cfm/media/articles/2025/USARIEM_is_updating_guidance_on_cold-weather_injuries
    name: read full story
  - url: https://mrdc.health.mil/index.cfm/media/articles/2024/reifman_receives_third_presidential_rank_award
    name: read full story
  - url: https://mrdc.health.mil/index.cfm/media/articles/2024/as_dr_mark_dertzbaugh_retires_MRDC_honors_his_thirty-plus_years_of_service
    name: read full story
  - url: http://www.jssor.com
    name: Bootstrap Slider
  - url: https://mrdc.health.mil/index.cfm/resources/employment/
    name: USAMRDC Engineer and Scientist Job Openings
  - url: https://webmail.apps.mil/mail/
    name: Outlook Webmail
  - url: https://mrdc.health.mil/index.cfm/about/jag/pl_115-92
    name: Public Law (PL) 115-92
  - url: https://www.safehelpline.org/
    name: safehelpline.org
  - url: https://www.armyresilience.army.mil/sharp/index.html
    name: armyresilience.army.mil
  - url: https://mrdc.health.mil/assets/docs/media/USAMRDC-Handbook.pdf
    name: [No text]
  - url: https://mrdc.health.mil/assets/docs/DoD_Suicide_Prevention_Research_Strategy.pdf
    name: [No text]
  - url: https://mrdc.health.mil/assets/docs/media/2019_Medical_Products_Book_Third_Edition.pdf
    name: [No text]
  - url: https://stem.health.mil/
    name: [No text]
  - url: https://www.mepcom.army.mil/Home/Contractors/
    name: [No text]
  - url: https://www.flickr.com/people/USAMRMC
    name: [No text]
  - url: https://mrdc.health.mil/index.cfm/ask
    name: Ask the Leadership »
  - url: https://www.army.mil/futures
    name: [No text]
  - url: https://mrdc.health.mil/
    name: [No text]
  - url: https://mrdc.health.mil/index.cfm/resources/mrdc_resources/dcshr
    name: View Full Details Here »
  - url: https://www.inscom.army.mil/isalute/
    name: [No text]
  - url: https://technologytransfer.health.mil/
    name: Medical Technology Transfer
  - url: https://mrdc-npi.health.mil/
    name: Submit New Product or Idea
  - url: https://mrdc.health.mil/privacy
    name: Privacy and Security
  - url: https://mrdc.health.mil/terms
    name: Terms of Use
  - url: https://mrdc.health.mil/foia
    name: Freedom of Information Act (FOIA)
  - url: https://dodcio.defense.gov/DoDSection508/Std_Stmt.aspx
    name: Accessibility
  - url: https://www.army.mil
    name: [No text]