url: https://nces.ed.gov/surveys/ntps/
name: National Teacher and Principal Survey (NTPS)
expected_update_frequency: yearly
tags: [education, nces, teachers, principals]
api_config:
  url: https://nces.ed.gov/api/ntps/surveys
  method: GET
  params:
    sort: year_desc
    limit: 1
  expected_fields:
    - total
    - surveys[0].school_year
    - surveys[0].components
    - surveys[0].status
    - surveys[0].release_date
    - surveys[0].teacher_sample_size
    - surveys[0].principal_sample_size
    - surveys[0].school_sample_size
  date_field: surveys[0].release_date
