url: https://nces.ed.gov/nationsreportcard/
name: National Assessment of Educational Progress
description: The National Assessment of Educational Progress (NAEP), also known as The Nation’s Report Card, is the largest ongoing, nationally representative assessment of education in the United States. Since 1969, NAEP has served as a vital measure of student achievement, providing valuable insights into academic performance and learning experiences across various subjects. Its results offer a comprehensive view of educational progress at the national level, across states, and in 27 urban districts.
omb_control_number: 1850-0928
expected_update_frequency: null
tags:
  - Education or Schools
  - Demographics
linked_urls:
  - url: https://nces.ed.gov/nationsreportcard/data/
    name: Explore Assessment Data
    resource_type: Supporting Documentation Page
  - url: https://www.nationsreportcard.gov/ndecore/
    name: NAEP Data Explorer
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.nationsreportcard.gov/nqt/
    name: NAEP Questions Tool
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.nationsreportcard.gov/profiles/stateprofile/
    name: State Profiles
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.nationsreportcard.gov/profiles/districtprofile/
    name: District Profiles
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://nces.ed.gov/nationsreportcard/studies/statemappingtool/#/
    name: State Mapping Data Tool
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.nationsreportcard.gov/dashboards/schools_dashboard.aspx
    name: Public, Private, Charter School Data
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://nces.ed.gov/nationsreportcard/about/inclusion.aspx#inclusion_accomm_data
    name: Inclusion/Accommodation Data
    resource_type: Data Repository or Listings page
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/variablesrudata.aspx
    name: Restricted-Use Datasets
    resource_type: Data Repository or Listings page
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx
    name: Statistical Software
    resource_type: Supporting Documentation Page
  - url: https://www.nationsreportcard.gov/api_documentation.aspx
    name: NAEP Data Service API
    resource_type: API Endpoint
  - url: https://nces.ed.gov/nationsreportcard/tdw/
    name: Technical Documentation
    resource_type: Supporting Documentation Page
  - url: https://www.nationsreportcard.gov/focus_on_naep/#/
    name: Focus on NAEP
    resource_type: Supporting Documentation Page
  - url: https://nces.ed.gov/nationsreportcard/guides/
    name: Intended Uses of NAEP
    resource_type: Supporting Documentation Page
  - url: https://nces.ed.gov/nationsreportcard/guides/scores_achv.aspx#achievement
    name: Achievement Level Descriptions
    resource_type: Supporting Documentation Page
  - url: https://nces.ed.gov/nationsreportcard/glossary.aspx
    name: Glossary
    resource_type: Supporting Documentation Page
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx#edsurvey
    name: EdSurvey
    resource_type: Supporting Documentation Page
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/datatools.aspx
    name: Data Available for Secondary Analysis
    resource_type: Supporting Documentation Page
  - url: https://www.nationsreportcard.gov
    name: Interactive Nation's Report Cards
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://nces.ed.gov/transfer.asp?location=naepdev.github.io/NAEP-Style-Guide/ux/index.html
    name: NAEP Style Guide on GitHub
    resource_type: Supporting Documentation Page
  - url: https://nces.ed.gov/nationsreportcard/frameworkhow.aspx
    name: NAEP Frameworks
    resource_type: Supporting Documentation Page
  - url: https://www.nationsreportcard.gov/itemmaps/?subj=MAT&grade=4&year=2024
    name: Item Maps
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.nationsreportcard.gov/arts_2016/files/2016_arts_appendix_tables.xls
    name: Arts 2016 Summary Data Tables (xls)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/arts_2016/files/2016_arts_appendix_tables.pdf
    name: Arts 2016 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
  - url: nationsreportcard.gov/civics/supporting_files/2022_civics_appendix.xlsx
    name: Civics 2022 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/geography/supporting_files/2018_geography_appendix.xlsx
    name: Geography 2018 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/geography/supporting_files/2018_geography_appendix.pdf
    name: Geography 2018 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/ltt/supporting_files/2022_appendix_ltt_9.xlsx
    name: Long-Term Trend Reading and Mathematics at Age 9 2022 Technical Appendix Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/ltt/supporting_files/2022_appendix_ltt_9.pdf
    name: Long-Term Trend Reading and Mathematics at Age 9 2022 Technical Appendix Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/ltt/supporting_files/2023_appendix_ltt_13.xlsx
    name: Long-Term Trend Reading and Mathematics at Age 13  2023 Technical Appendix Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/ltt/supporting_files/2023_appendix_ltt_13.pdf
    name: Long-Term Trend Reading and Mathematics at Age 13 2023 Technical Appendix Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/reports/mathematics/2024/g4_8/supporting-files/2024_technical_appendix_math_national.xlsx
    name: Mathematics (National, State & District) 2024 Technical Appendix Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/reports/mathematics/2024/g4_8/supporting-files/2024_technical_appendix_math_national.pdf
    name: Mathematics (National, State & District) 2024 Technical Appendix Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/mathematics/supportive_files/2019_appendix_math_g12.xlsx
    name: Mathematics (Grade 12) 2019 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/mathematics/supportive_files/2019_appendix_math_g12.pdf
    name: Mathematics (Grade 12) 2019 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/reports/reading/2024/g4_8/supporting-files/2024_technical_appendix_reading_national.xlsx
    name: Reading (National, State & District) 2024 Technical Appendix Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/reports/reading/2024/g4_8/supporting-files/2024_technical_appendix_reading_national.pdf
    name: Reading (National, State & District) 2024 Technical Appendix Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/reading/supportive_files/2019_appendix_reading_g12.xlsx
    name: Reading (Grade 12) 2019 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/reading/supportive_files/2019_appendix_reading_g12.pdf
    name: Reading (Grade 12) 2019 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/science/supporting_files/2019_appendix_sci.xlsx
    name: Science 2019 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/science/supporting_files/2019_appendix_sci.pdf
    name: Science 2019 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/tel/files/2018_TEL_appendix_tables.xlsx
    name: Technology Engineering Literacy 2018 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/tel/files/2018_TEL_appendix_tables.pdf
    name: Technology Engineering Literacy 2018 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
  - url: https://www.nationsreportcard.gov/ushistory/supporting_files/2022_history_appendix.xlsx
    name: U.S. History 2022 Summary Data Tables (xlsx)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/reading_2013/vocabulary/files/2013_Reading_Vocabulary_Appendix_Tables.xls
    name: Vocabulary 2013 Summary Data Tables (xls)
    resource_type: Data File (Excel)
  - url: https://www.nationsreportcard.gov/reading_2013/vocabulary/files/2013_Reading_Vocabulary_Appendix_Tables.pdf
    name: Vocabulary 2013 Summary Data Tables (pdf)
    resource_type: Data File (PDF)
