url: https://bjs.ojp.gov/data-collection/school-crime-supplement-scs
name: School Crime Supplement (SCS)
expected_update_frequency: yearly
tags: [justice, education, crime, survey]
api_config:
  url: https://bjs.ojp.gov/api/v1/collections/scs
  method: GET
  params:
    sort: -year
    page[size]: 1
  expected_fields:
    - meta.total
    - data[0].id
    - data[0].type
    - data[0].attributes.year
    - data[0].attributes.title
    - data[0].attributes.status
    - data[0].attributes.published_date
    - data[0].attributes.sample_size
    - data[0].attributes.response_rate
  date_field: data[0].attributes.published_date
