url: https://www.census.gov/programs-surveys/household-pulse-survey.html
name: Household Pulse Survey
expected_update_frequency: monthly
tags: [census, covid, survey]
api_config:
  url: https://api.census.gov/data/2023/hps/phase3.9
  method: GET
  params:
    get: WEEK,EST_MSE
    for: us:1
    key: CENSUS_API_KEY
  headers:
    User-Agent: DemoAdvisors/1.0
  expected_fields:
    - [0].length  # Header row length
    - [1].length  # Data row length
    - [0][0]      # First column name
    - [1][0]      # First data value
  date_field: null  # Use Last-Modified header from response
