url: https://www.whitehouse.gov/invest/
name: White House Investing in America
expected_update_frequency: daily
tags: [white-house, infrastructure, investment]
api_config:
  url: https://www.whitehouse.gov/wp-json/wp/v2/posts
  method: GET
  params:
    categories: 234  # Investing in America category
    per_page: 1
    orderby: date
    order: desc
  expected_fields:
    - [0].id
    - [0].date
    - [0].modified
    - [0].slug
    - [0].status
    - [0].type
    - [0].title.rendered
    - [0].content.rendered
  date_field: [0].modified
