url: https://www.atf.gov/firearms/listing-federal-firearms-licensees
name: ATF Federal Firearms Licensees (FFL)
expected_update_frequency: monthly
tags: [justice, firearms, licensing]
api_config:
  url: https://www.atf.gov/firearms/docs/undefined/federal-firearms-licensees-by-state
  method: GET
  headers:
    Accept: application/json
  expected_fields:
    - meta.total
    - data.month
    - data.year
    - data.last_updated
    - data.states[0].state_name
    - data.states[0].total_licenses
    - data.states[0].license_types
  date_field: data.last_updated
