url: https://enforcedata.dol.gov/views/data_catalogs.php
name: Department of Labor Enforcement Data
expected_update_frequency: monthly
tags: [labor, enforcement, workplace]
api_config:
  url: https://enforcedata.dol.gov/api/v1/latest_enforcement
  method: GET
  params:
    agency: all
  expected_fields:
    - meta.total_records
    - meta.last_updated
    - data[0].agency
    - data[0].case_id
    - data[0].trade_name
    - data[0].legal_name
    - data[0].street
    - data[0].city
    - data[0].state
    - data[0].zip_code
    - data[0].naics_code
    - data[0].inspection_type
    - data[0].violations_found
    - data[0].total_penalty
  date_field: meta.last_updated
