url: https://ffiec.cfpb.gov/data-browser/
name: Home Mortgage Disclosure Act (HMDA) Data
expected_update_frequency: quarterly
tags: [financial, housing, mortgage, cfpb]
api_config:
  url: https://ffiec.cfpb.gov/v2/public-data/modified-lar/2023
  method: GET
  params:
    limit: 1
  expected_fields:
    - meta.institution_count
    - meta.filing_year
    - meta.last_updated
    - data[0].lei
    - data[0].uli
    - data[0].loan_type
    - data[0].loan_purpose
    - data[0].loan_amount
    - data[0].action_taken
    - data[0].state_code
    - data[0].county_code
    - data[0].census_tract
  date_field: meta.last_updated
