url: https://www.cdc.gov/nchs/nhanes/index.htm
name: National Health and Nutrition Examination Survey (NHANES)
expected_update_frequency: yearly
tags: [health, cdc, survey, nutrition]
api_config:
  url: https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx
  method: GET
  params:
    Component: Demographics
    CycleBeginYear: 2021
  expected_fields:
    - cycle_begin_year
    - cycle_end_year
    - component
    - doc_file
    - data_file
    - date_published
    - component_description
    - file_name
  date_field: date_published
