url: https://nces.ed.gov/nationsreportcard/nies/
name: National Indian Education Study
expected_update_frequency: null
tags:
  - ed
  - education
linked_urls:
  - url: https://nces.ed.gov/nationsreportcard/arts/
    name: Arts
  - url: https://nces.ed.gov/nationsreportcard/civics/
    name: Civics
  - url: https://nces.ed.gov/nationsreportcard/economics/
    name: Economics
  - url: https://nces.ed.gov/nationsreportcard/geography/
    name: Geography
  - url: https://nces.ed.gov/nationsreportcard/mathematics/
    name: Mathematics
  - url: https://nces.ed.gov/nationsreportcard/reading/
    name: Reading
  - url: https://nces.ed.gov/nationsreportcard/science/
    name: Science
  - url: https://nces.ed.gov/nationsreportcard/tel/
    name: Technology & Engineering Literacy
  - url: https://nces.ed.gov/nationsreportcard/ushistory/
    name: U.S. History
  - url: https://nces.ed.gov/nationsreportcard/writing/
    name: Writing
  - url: https://nces.ed.gov/nationsreportcard/state/
    name: NAEP State Results
  - url: https://nces.ed.gov/nationsreportcard/tuda/
    name: Trial Urban District Results
  - url: https://nces.ed.gov/nationsreportcard/participating/private_nonpublic.aspx#performing
    name: Private School Results
  - url: https://nces.ed.gov/nationsreportcard/about/covid19.aspx
    name: NAEP COVID-19 Resources
  - url: https://nces.ed.gov/nationsreportcard/about/covid19_spanish.aspx
    name: NAEP Recursos sobre el COVID-19
  - url: https://ies.ed.gov/schoolsurvey/
    name: 2021 School Survey
  - url: https://nces.ed.gov/nationsreportcard/about/calendar.aspx
    name: Assessment Schedule
  - url: https://nces.ed.gov/nationsreportcard/guides/
    name: Intended Meaning of NAEP
  - url: https://nces.ed.gov/nationsreportcard/guides/scores_achv.aspx
    name: How Results Are Reported
  - url: https://nces.ed.gov/nationsreportcard/guides/groups.aspx
    name: Student Groups
  - url: https://nces.ed.gov/nationsreportcard/guides/statsig.aspx
    name: Statistical Significance
  - url: https://www.nationsreportcard.gov/
    name: Explore recent assessment results on The Nation's Report Card.
  - url: https://nces.ed.gov/nationsreportcard/data/
    name: Explore Assessment Data
  - url: https://www.nationsreportcard.gov/ndecore/
    name: NAEP Data Explorer
  - url: https://www.nationsreportcard.gov/nqt/
    name: NAEP Questions Tool
  - url: https://www.nationsreportcard.gov/profiles/stateprofile/
    name: State Profiles
  - url: https://www.nationsreportcard.gov/profiles/districtprofile/
    name: District Profiles
  - url: https://nces.ed.gov/nationsreportcard/studies/statemappingtool/#/
    name: State Mapping Data Tool
  - url: https://www.nationsreportcard.gov/dashboards/schools_dashboard.aspx
    name: Public, Private, Charter School Data
  - url: https://nces.ed.gov/nationsreportcard/about/inclusion.aspx#inclusion_accomm_data
    name: Inclusion/Accommodation Data
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/variablesrudata.aspx
    name: Restricted-Use Datasets
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx
    name: Statistical Software
  - url: https://www.nationsreportcard.gov/api_documentation.aspx
    name: NAEP API
  - url: https://nces.ed.gov/datatools/
    name: Other NCES Data
  - url: https://nces.ed.gov/nationsreportcard/tdw/
    name: Technical Documentation
  - url: https://www.nationsreportcard.gov/focus_on_naep/#/
    name: Focus on NAEP
  - url: https://nces.ed.gov/nationsreportcard/guides/
    name: Intended Uses of NAEP
  - url: https://nces.ed.gov/nationsreportcard/guides/scores_achv.aspx#achievement
    name: Achievement Level Descriptions
  - url: https://nces.ed.gov/nationsreportcard/glossary.aspx
    name: Glossary
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/
    name: News & Updates
  - url: https://nces.ed.gov/nationsreportcard/tdw/
    name: Technical Documentation
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx#edsurvey
    name: EdSurvey
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/datatools.aspx
    name: Data Available for Secondary Analysis
  - url: https://nces.ed.gov/pubsearch/index.asp?PubSectionID=1&HasSearched=1&pubspagenum=1&sort=3&order=0&L1=&L2=&searchstring=&searchtype=AND&searchcat2=&searchcat=title&pagesize=15&searchmonth=1&searchyear=1980&datetype=%3E%3D&pubtype=018&surveyname=&surveyid=031\u00a2ername=NCES\u00a2er=NCES
    name: Special Studies and Technical/Methodological Reports
  - url: https://nces.ed.gov/pubsearch/index.asp?PubSectionID=1&HasSearched=1&pubspagenum=1&sort=3&order=0&L1=&L2=&searchstring=&searchtype=AND&searchcat2=&searchcat=title&pagesize=15&searchmonth=1&searchyear=1980&datetype=%3E%3D&pubtype=&surveyname=National+Assessment+of+Educational+Progress&surveyid=031\u00a2ername=NCES\u00a2er=NCES
    name: Browse NAEP Publications
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/training.aspx
    name: Conferences and Training
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/papers.aspx
    name: Research Library
  - url: https://www.nationsreportcard.gov
    name: Interactive Nation's Report Cards
  - url: https://nces.ed.gov/transfer.asp?location=naepdev.github.io/NAEP-Style-Guide/ux/index.html
    name: NAEP Style Guide on GitHub
  - url: https://nces.ed.gov/nationsreportcard/educators/
    name: News & Updates
  - url: https://nces.ed.gov/nationsreportcard/frameworkhow.aspx
    name: NAEP Frameworks
  - url: https://www.nationsreportcard.gov/itemmaps/?subj=MAT&grade=4&year=2019
    name: Performance Scales and Achievement Levels
  - url: https://nces.ed.gov/nationsreportcard/educators/default.aspx#student_experiences
    name: Student Experiences and NAEP Performance
  - url: https://www.nationsreportcard.gov/takenaepnow/home
    name: Take NAEP Now
  - url: https://nces.ed.gov/nationsreportcard/blog/dataset_mathematics.aspx
    name: New NAEP Dataset Offers Insights into Students' Mathematics Reasoning.
  - url: https://nces.ed.gov/transfer.asp?location=naepdev.github.io/NAEP-Style-Guide/ux/index.html
    name: The NAEP Style Guide is interactive, open sourced, and available to the public!
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/
    name: News & Updates
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx#edsurvey
    name: EdSurvey
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/datatools.aspx
    name: NAEP Data Available for Secondary Analysis
  - url: https://nces.ed.gov/nationsreportcard/data/
    name: Data Tools
  - url: https://www.nationsreportcard.gov
    name: Report Cards
  - url: https://www.nationsreportcard.gov/api_documentation.aspx
    name: NAEP API
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx
    name: Statistical Software
  - url: https://nces.ed.gov/nationsreportcard/researchcenter/training.aspx
    name: Training and Conferences
  - url: https://nces.ed.gov/pubsearch/index.asp?PubSectionID=1&HasSearched=1&pubspagenum=1&sort=3&order=0&L1=&L2=&searchstring=&searchtype=AND&searchcat2=&searchcat=title&pagesize=15&searchmonth=1&searchyear=1980&datetype=%3E%3D&pubtype=&surveyname=National+Assessment+of+Educational+Progress&surveyid=031\u00a2ername=NCES\u00a2er=NCES
    name: Browse Publications
  - url: https://nces.ed.gov/nationsreportcard/tdw/
    name: Technical Documentation
  - url: https://nces.ed.gov/nationsreportcard/participating/
    name: Get Ready for NAEP
  - url: https://nces.ed.gov/nationsreportcard/parents/
    name: What You Need to Know About NAEP
  - url: https://nces.ed.gov/nationsreportcard/pdf/parents/2012469.pdf
    name: NAEP and Your ChildClick to open pdf.
  - url: https://nces.ed.gov/nationsreportcard/parents/
    name: How NAEP Shapes Educational Policy
  - url: https://nces.ed.gov/nationsreportcard/participating/
    name: Get Ready for NAEP
  - url: https://nces.ed.gov/nationsreportcard/students/
    name: What is NAEP?
  - url: https://nces.ed.gov/nationsreportcard/students/default.aspx#questions
    name: What Questions Are On the Test?
  - url: https://www.youtube.com/watch?v=8drjkhe0iQU
    name: Why Should You Participate?
  - url: https://www.nationsreportcard.gov/takenaepnow/home
    name: Take NAEP Now
  - url: https://nces.ed.gov/nationsreportcard/participating/
    name: Get Ready for NAEP
  - url: https://nces.ed.gov/nationsreportcard/participating/schools.aspx
    name: Public Schools
  - url: https://nces.ed.gov/nationsreportcard/participating/private_nonpublic.aspx
    name: Private Schools
  - url: https://www.nationsreportcard.gov/takenaepnow/home
    name: Take NAEP Now
  - url: https://www.nationsreportcard.gov/dashboards/schools_dashboard.aspx
    name: Public, Private, Charter School Data
  - url: https://nces.ed.gov/nationsreportcard/about/policy_practice.aspx
    name: How NAEP Shapes Educational Policy
  - url: https://www.nationsreportcard.gov/profiles/stateprofile/
    name: How is My State Performing?
  - url: https://www.nationsreportcard.gov/profiles/districtprofile?chort=1&sub=MAT&sj=XQ&sfj=NL&st=MN&year=2019R3
    name: How is My District Performing?
  - url: https://nces.ed.gov/nationsreportcard/educators/default.aspx#student_experiences
    name: Survey Questionnaires and NAEP Performance
  - url: https://ies.ed.gov/schoolsurvey/
    name: 2021 School Survey
  - url: https://nces.ed.gov/nationsreportcard/educators/
    name: Resources for Educators
  - url: https://nces.ed.gov/nationsreportcard/educators/default.aspx#student_experiences
    name: Student Experiences and NAEP Performance
  - url: https://www.nationsreportcard.gov/takenaepnow/home
    name: Take NAEP Now
  - url: https://nces.ed.gov/nationsreportcard/nqt/
    name: Sample Questions
  - url: https://nces.ed.gov/nationsreportcard/frameworkhow.aspx
    name: NAEP Frameworks
  - url: https://nces.ed.gov/nationsreportcard/pubs_newsroom/
    name: Newsroom
  - url: https://nces.ed.gov/nationsreportcard/blog/
    name: NAEP Blog
  - url: https://www.nationsreportcard.gov/media_video_archive.aspx
    name: NAEP Videos
  - url: https://nces.ed.gov/pubsearch/index.asp?PubSectionID=1&HasSearched=1&pubspagenum=1&sort=3&order=0&L1=&L2=&searchstring=&searchtype=AND&searchcat2=&searchcat=title&pagesize=15&searchmonth=1&searchyear=1980&datetype=%3E%3D&pubtype=&surveyname=National+Assessment+of+Educational+Progress&surveyid=031\u00a2ername=NCES\u00a2er=NCES
    name: Publications
  - url: https://nces.ed.gov/pubsearch/index.asp?PubSectionID=1&HasSearched=1&pubspagenum=1&sort=3&order=0&L1=&L2=&searchstring=&searchtype=AND&searchcat2=&searchcat=title&pagesize=15&searchmonth=1&searchyear=1980&datetype=%3E%3D&pubtype=&surveyname=National+Assessment+of+Educational+Progress&surveyid=031\u00a2ername=NCES\u00a2er=NCES
    name: Customize Search (by title, keyword, year, subject)
  - url: https://nces.ed.gov/pubsearch/getpubcats.asp?sid=031
    name: Search by Subject
  - url: https://www.nationsreportcard.gov
    name: The Nation's Report Cards (by subject)
  - url: https://nces.ed.gov/pubsearch/getpubcats.asp?sid=031&opencat=Brochures
    name: Brochures
  - url: https://nces.ed.gov/nationsreportcard/about/calendar.aspx
    name: Assessments
  - url: https://nces.ed.gov/nationsreportcard/about/events.aspx
    name: Events
  - url: https://nces.ed.gov/nationsreportcard/pubs_newsroom/
    name: Publications
  - url: https://www.nationsreportcard.gov/sq_students_views_2015/
    name: Survey Questionnaires
  - url: https://nces.ed.gov/nationsreportcard/studies/gaps/
    name: Achievement Gaps
  - url: https://nces.ed.gov/nationsreportcard/studies/orf/
    name: Oral Reading Fluency
  - url: https://nces.ed.gov/nationsreportcard/studies/inclusion/
    name: Inclusion Rates of Students with Disabilities
  - url: https://nces.ed.gov/nationsreportcard/studies/statemapping/
    name: Mapping State Proficiency
  - url: https://nces.ed.gov/nationsreportcard/studies/naep_timss/
    name: Linking NAEP and TIMSS
  - url: https://www.nationsreportcard.gov/focus_on_naep/#/
    name: Focus on NAEP
  - url: https://www.nationsreportcard.gov/process_data/
    name: Process Data
  - url: https://nces.ed.gov/nationsreportcard/puertorico/
    name: Puerto Rico Mathematics Studies
  - url: https://nces.ed.gov/nationsreportcard/puertorico/sp.aspx
    name: Estudios de matematicas en Puerto Rico
  - url: https://nces.ed.gov/nationsreportcard/hsts/
    name: High School Transcript Study
  - url: https://nces.ed.gov/nationsreportcard/nies/
    name: National Indian Education Study
  - url: https://nces.ed.gov/nationsreportcard/ltt/
    name: Long-Term Trend Assessment
  - url: https://nces.ed.gov/nationsreportcard/pubs_newsroom/
    name: Newsroom
  - url: https://nces.ed.gov/nationsreportcard/blog
    name: NAEP Plus Blog
  - url: https://ies.ed.gov/newsflash/#nces
    name: Subscribe to NAEP NewsFlash
  - url: https://www.youtube.com/channel/UCZwflFwrYalirN1kbbYs9tg
    name: NAEP YouTube Channel
  - url: https://www.nationsreportcard.gov/media_video_archive.aspx
    name: Archive
  - url: https://nces.ed.gov/transfer.asp?location=naepdev.github.io/NAEP-Style-Guide/ux/index.html
    name: NAEP Style Guide on GitHub
  - url: https://www.nationsreportcard.gov/ltt/?age=9/
    name: Explore Results from the 2022-2023 Long-Term Trend Assessments for Reading & Mathematics.
  - url: https://nces.ed.gov/nationsreportcard/about/
    name: Program Overview
  - url: https://www.youtube.com/watch?v=8drjkhe0iQU
    name: Why is NAEP Important?
  - url: https://nces.ed.gov/nationsreportcard/experience/survey_questionnaires.aspx
    name: Survey Questionnaires
  - url: https://www.nationsreportcard.gov/takenaepnow/home
    name: Take NAEP Now
  - url: https://nces.ed.gov/nationsreportcard/experience/booklets.aspx
    name: Sample Questions Booklets
  - url: https://nces.ed.gov/nationsreportcard/assessments/frameworks.aspx
    name: Assessment Frameworks
  - url: https://nces.ed.gov/nationsreportcard/assessment_process/
    name: Assessment Process
  - url: https://nces.ed.gov/nationsreportcard/experience/
    name: Experience an Assessment
  - url: https://nces.ed.gov/nationsreportcard/about/faqs.aspx
    name: FAQs
  - url: https://nces.ed.gov/nationsreportcard/about/organization_governance.aspx
    name: Organization and Governance
  - url: https://nces.ed.gov/ncestaff/SurvDetl.asp?surveyID=031
    name: NAEP Staff
  - url: https://nces.ed.gov/nationsreportcard/about/calendar.aspx
    name: Assessment Calendar
  - url: https://nces.ed.gov/nationsreportcard/about/events.aspx
    name: Events
  - url: https://nces.ed.gov/nationsreportcard/about/advancements.aspx#modernization
    name: Using School Internet for NAEP
  - url: https://nces.ed.gov/nationsreportcard/about/timeline.aspx
    name: History and Innovation
  - url: https://nces.ed.gov/nationsreportcard/dba/
    name: Digitally Based Assessments
  - url: https://nces.ed.gov/nationsreportcard/about/policy_practice.aspx
    name: How is NAEP shaping educational policy and legislation?
  - url: https://nces.ed.gov/nationsreportcard/blog/modernizing_naep_assessments_faq.aspx
    name: Modernizing NAEP Assessments FAQ about Current and Future Activities
  - url: https://nces.ed.gov/nationsreportcard/contactus.aspx
    name: ASK A QUESTION
  - url: https://nces.ed.gov/nationsreportcard/participating/
    name: NAEP 2022 data collection is currently taking place.
  - url: https://nces.ed.gov/pubsearch/pubsinfo.asp?pubid=2021018
    name: The National Indian Education Study 2019
  - url: https://oese.ed.gov/offices/office-of-indian-education/indian-education-national-activities/
    name: NIES and the Office of Indian Education
  - url: https://nces.ed.gov/nationsreportcard/nies/study_overview.aspx
    name: National Indian Education Study Study Overview
  - url: https://nces.ed.gov/nationsreportcard/subject/nies/nies_2019_student_teacher_data_companion.pdf
    name: 2019 NIES Data Companion Overview
  - url: https://nces.ed.gov/nationsreportcard/subject/nies/nies_2019_student_responses.xlsx
    name: 2019 Student Responses
  - url: https://nces.ed.gov/nationsreportcard/subject/nies/nies_2019_teacher_responses.xlsx
    name: 2019 Teacher Responses
  - url: https://nces.ed.gov/nationsreportcard/nies/about_survey.aspx
    name: About the Survey
  - url: https://nces.ed.gov/nationsreportcard/nies/questionnaire.aspx
    name: Survey Questionnaires
  - url: https://nces.ed.gov/nationsreportcard/subject/participating/2019/nies_facts_for_associate_deputy_directors.pdf
    name: NIES Factsheet
  - url: https://www2.ed.gov/about/offices/list/oese/oie/index.html
    name: Office of Indian Education (OIE)
  - url: https://nces.ed.gov/nationsreportcard/glossary.aspx#bie
    name: Bureau of Indian Education
  - url: https://nces.ed.gov/nationsreportcard/subject/nies/2019_bie_sdel_rates.pdf
    name: Inclusion and Accommodation Data from the 2019 Study
  - url: https://nces.ed.gov/nationsreportcard/nies/questionnaire.aspx
    name: Questionnaires
  - url: https://nces.ed.gov/nationsreportcard/tdw/analysis/summary_rules_minimum.aspx
    name: Minimum School and Student Sample Sizes for Reporting Group Results
  - url: https://nces.ed.gov/pubs2008/nativetrends
    name: Status and Trends in the Education of American Indians and Alaska Natives 2008
  - url: https://nces.ed.gov/pubs2005/nativetrends
    name: Status and Trends report
  - url: https://nces.ed.gov/pubsearch/pubsinfo.asp?pubid=2009321
    name: School Characteristics
  - url: https://nces.ed.gov/pubsearch/pubsinfo.asp?pubid=2009322
    name: School Library Media Centers
  - url: https://nces.ed.gov/pubsearch/pubsinfo.asp?pubid=2009323
    name: Principals
  - url: https://nces.ed.gov/pubsearch/pubsinfo.asp?pubid=2009324
    name: Teachers
  - url: https://files.eric.ed.gov/fulltext/ED485835.pdf
    name: American Indian and Alaska Native Children Findings From the Base Year of the Early Childhood Longitudinal Study, Birth Cohort (ECLS-B)
  - url: https://eric.ed.gov/
    name: ERIC
  - url: https://nces.ed.gov/nationsreportcard/about/faqs.aspx
    name: Learn More