url: https://www.cdc.gov/nchs/nsfg/index.htm
name: National Survey of Family Growth (NSFG)
expected_update_frequency: yearly
tags: [health, cdc, survey, family]
api_config:
  url: https://www.cdc.gov/nchs/nsfg/nsfg_json/metadata.json
  method: GET
  expected_fields:
    - current_release
    - years_covered
    - last_updated
    - sample_size
    - response_rate
    - data_files
    - documentation
    - questionnaires
  date_field: last_updated
