url: https://www.census.gov/programs-surveys/nsch.html
name: National Survey of Children's Health (NSCH)
expected_update_frequency: yearly
tags: [census, health, children, survey]
api_config:
  url: https://api.census.gov/data/2023/nsch
  method: GET
  params:
    get: GROUP
    for: us:1
    key: CENSUS_API_KEY
  headers:
    User-Agent: DemoAdvisors/1.0
  expected_fields:
    - [0].length  # Header row length
    - [1].length  # Data row length
    - [0][0]      # First column name
    - [1][0]      # First data value
  date_field: null  # Use Last-Modified header from response
