url: https://www.cdc.gov/dhdsp/maps/atlas/index.htm
name: Interactive Atlas of Heart Disease and Stroke
expected_update_frequency: yearly
tags: [health, cdc, cardiovascular, mapping]
api_config:
  url: https://services7.arcgis.com/2G5FqXJolXA0wZGO/arcgis/rest/services/HeartAtlas/FeatureServer/0/query
  method: GET
  params:
    where: 1=1
    outFields: OBJECTID,Year,LastUpdate,DataSource
    returnGeometry: false
    orderByFields: Year DESC
    resultRecordCount: 1
    f: json
  expected_fields:
    - features[0].attributes.OBJECTID
    - features[0].attributes.Year
    - features[0].attributes.LastUpdate
    - features[0].attributes.DataSource
  date_field: features[0].attributes.LastUpdate
