url: https://www.justice.gov/usao/resources/annual-statistical-reports
name: DOJ Annual Statistical Reports
expected_update_frequency: null
tags:
  - DOJ
  - justice
linked_urls:
  - url: https://www.justice.gov/
    name: U.S. Department of Justice
  - url: https://www.justice.gov/usao/resources/annual-statistical-reports
    name: Annual Statistical Reports
  - url: https://www.justice.gov/usao/resources/journal-of-federal-law-and-practice
    name: DOJ Journal
  - url: https://www.justice.gov/usao/page/file/1390446/dl?inline
    name: 2020
  - url: https://www.justice.gov/usao/page/file/1476856/dl?inline
    name: 2021
  - url: https://www.justice.gov/usao/file/1574596/dl?inline
    name: 2022
  - url: https://www.justice.gov/usao/media/1343726/dl?inline
    name: 2023
  - url: https://www.justice.gov/usao/reading_room/reports/asr2010/10statrpt.pdf
    name: 2010
  - url: https://www.justice.gov/usao/reading_room/reports/asr2011/11statrpt.pdf
    name: 2011
  - url: https://www.justice.gov/usao/reading_room/reports/asr2012/12statrpt.pdf
    name: 2012
  - url: https://www.justice.gov/usao/reading_room/reports/asr2013/13statrpt.pdf
    name: 2013
  - url: https://www.justice.gov/sites/default/files/usao/pages/attachments/2015/03/23/14statrpt.pdf
    name: 2014
  - url: https://www.justice.gov/media/823441/dl?inline
    name: 2015
  - url: https://www.justice.gov/usao/page/file/988896/dl?inline
    name: 2016
  - url: https://www.justice.gov/usao/page/file/1081801/dl?inline
    name: 2017
  - url: https://www.justice.gov/usao/page/file/1199336/dl?inline
    name: 2018
  - url: https://www.justice.gov/usao/page/file/1285951/dl?inline
    name: 2019
  - url: https://www.justice.gov/usao/reading_room/reports/asr2000/00statrpt.pdf
    name: 2000
  - url: https://www.justice.gov/usao/reading_room/reports/asr2001/01statrpt.pdf
    name: 2001
  - url: https://www.justice.gov/usao/reading_room/reports/asr2002/02_stat_book.pdf
    name: 2002
  - url: https://www.justice.gov/usao/reading_room/reports/asr2003/03_STAT_Report.pdf
    name: 2003
  - url: https://www.justice.gov/usao/reading_room/reports/asr2004/asr2004.pdf
    name: 2004
  - url: https://www.justice.gov/usao/reading_room/reports/asr2005/05statrpt.pdf
    name: 2005
  - url: https://www.justice.gov/usao/reading_room/reports/asr2006/06statrpt.pdf
    name: 2006
  - url: https://www.justice.gov/usao/reading_room/reports/asr2007/07statrpt.pdf
    name: 2007
  - url: https://www.justice.gov/usao/reading_room/reports/asr2008/08statrpt.pdf
    name: 2008
  - url: https://www.justice.gov/usao/reading_room/reports/asr2009/09statrpt.pdf
    name: 2009
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1990.pdf
    name: 1990
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1991.pdf
    name: 1991
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1992.pdf
    name: 1992
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1993.pdf
    name: 1993
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1994.pdf
    name: 1994
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1995.pdf
    name: 1995
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1996.pdf
    name: 1996
  - url: https://www.justice.gov/usao/reading_room/reports/1990s/STATISTICAL_REPORT_FISCAL_YEAR_1997.pdf
    name: 1997
  - url: https://www.justice.gov/usao/reading_room/reports/asr1998/98statrpt.pdf
    name: 1998
  - url: https://www.justice.gov/usao/reading_room/reports/asr1999/99statrpt.pdf
    name: 1999
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1980.pdf
    name: 1980
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1981.pdf
    name: 1981
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1982.pdf
    name: 1982
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1983.pdf
    name: 1983
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1984.pdf
    name: 1984
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1985.pdf
    name: 1985
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1986.pdf
    name: 1986
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1987.pdf
    name: 1987
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1988.pdf
    name: 1988
  - url: https://www.justice.gov/usao/reading_room/reports/1980s/STATISTICAL_REPORT_FISCAL_YEAR_1989.pdf
    name: 1989
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1970.pdf
    name: 1970
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1971.pdf
    name: 1971
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1972.pdf
    name: 1972
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1973.pdf
    name: 1973
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1974.pdf
    name: 1974
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1975.pdf
    name: 1975
  - url: https://www.justice.gov/media/987941/dl?inline
    name: 1976
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1977.pdf
    name: 1977
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1978.pdf
    name: 1978
  - url: https://www.justice.gov/usao/reading_room/reports/1970s/STATISTICAL_REPORT_FISCAL_YEAR_1979.pdf
    name: 1979
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1960.pdf
    name: 1960
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1961.pdf
    name: 1961
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1962.pdf
    name: 1962
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1963.pdf
    name: 1963
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1964.pdf
    name: 1964
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1965.pdf
    name: 1965
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1966.pdf
    name: 1966
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1967.pdf
    name: 1967
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1968.pdf
    name: 1968
  - url: https://www.justice.gov/usao/reading_room/reports/1960s/STATISTICAL_REPORT_FISCAL_YEAR_1969.pdf
    name: 1969
  - url: https://www.justice.gov/usao/reading_room/reports/1950s/STATISTICAL_REPORT_FISCAL_YEAR_1955.pdf
    name: 1955
  - url: https://www.justice.gov/usao/reading_room/reports/1950s/STATISTICAL_REPORT_FISCAL_YEAR_1956.pdf
    name: 1956
  - url: https://www.justice.gov/usao/reading_room/reports/1950s/STATISTICAL_REPORT_FISCAL_YEAR_1957.pdf
    name: 1957
  - url: https://www.justice.gov/usao/reading_room/reports/1950s/STATISTICAL_REPORT_FISCAL_YEAR_1958_Jan.pdf
    name: Jan 1958
  - url: https://www.justice.gov/usao/reading_room/reports/1950s/STATISTICAL_REPORT_FISCAL_YEAR_1958_Sept.pdf
    name: Sept 1958
  - url: https://www.justice.gov/usao/reading_room/reports/1950s/STATISTICAL_REPORT_FISCAL_YEAR_1959.pdf
    name: 1959
  - url: https://www.justice.gov/archives/doj-archive
    name: Archives
