url: https://wonder.cdc.gov/
name: Wide-ranging ONline Data for Epidemiologic Research (WONDER)
expected_update_frequency: monthly
tags: [health, cdc, epidemiology, research]
api_config:
  url: https://wonder.cdc.gov/wonder/help/WONDER-API.html
  method: POST
  headers:
    Content-Type: application/x-www-form-urlencoded
  params:
    accept_datause_restrictions: true
    stage: request
    saved_id: D76
    action: getCurrentVersion
  expected_fields:
    - version
    - release_date
    - databases[0].name
    - databases[0].id
    - databases[0].last_updated
    - databases[0].years_covered
  date_field: databases[0].last_updated
