url: https://wonder.cdc.gov/nndss/nndss_weekly_tables_menu.html
name: National Notifiable Diseases Surveillance System (NNDSS)
expected_update_frequency: weekly
tags: [health, cdc, disease-surveillance]
api_config:
  url: https://data.cdc.gov/resource/rpjh-gpg8.json
  method: GET
  params:
    $order: mmwr_week DESC
    $limit: 1
  expected_fields:
    - mmwr_year
    - mmwr_week
    - reporting_area
    - disease
    - current_week
    - current_week_flag
    - previous_52_weeks_max
    - previous_52_weeks_cases
    - previous_52_weeks_flag
  date_field: mmwr_week  # Combined with mmwr_year
