url: https://www.cdc.gov/tb/statistics/default.htm
name: CDC Tuberculosis Surveillance Data
expected_update_frequency: yearly
tags: [health, cdc, tb-surveillance]
api_config:
  url: https://data.cdc.gov/resource/4n8r-wqf3.json
  method: GET
  params:
    $order: year DESC
    $limit: 1
  expected_fields:
    - year
    - state
    - cases
    - case_rate_per_100000
    - completion_of_therapy
    - directly_observed_therapy
    - last_updated
  date_field: last_updated
