url: https://www.cdc.gov/hiv/library/reports/hiv-surveillance.html
name: CDC HIV/AIDS Surveillance Reports
expected_update_frequency: yearly
tags: [health, cdc, hiv-surveillance]
api_config:
  url: https://data.cdc.gov/resource/yrbw-k5vy.json
  method: GET
  params:
    $order: year DESC
    $limit: 1
  expected_fields:
    - year
    - state
    - age_group
    - race_ethnicity
    - transmission_category
    - cases
    - estimated_cases
    - rates_per_100000
    - data_release_date
  date_field: data_release_date
