url: https://www.cdc.gov/cancer/npcr/index.htm
name: National Program of Cancer Registries (NPCR)
expected_update_frequency: yearly
tags: [health, cdc, cancer, registry]
api_config:
  url: https://www.cdc.gov/wcms/vizdata/cancer/npcr/status.json
  method: GET
  expected_fields:
    - last_updated
    - reporting_year
    - states_reporting
    - total_cases
    - completeness_percent
    - timeliness_percent
    - quality_metrics
  date_field: last_updated
