url: https://seer.cancer.gov/data/
name: Surveillance, Epidemiology, and End Results (SEER)
expected_update_frequency: yearly
tags: [health, nih, cancer, registry]
api_config:
  url: https://api.seer.cancer.gov/api/v1/databases
  method: GET
  headers:
    Accept: application/json
    X-API-Key: SEER_API_KEY
  expected_fields:
    - current_release
    - last_updated
    - databases[0].name
    - databases[0].year
    - databases[0].release_date
    - databases[0].coverage
    - databases[0].population_covered
  date_field: last_updated
