url: https://addhealth.cpc.unc.edu/data/
name: National Longitudinal Study of Adolescent to Adult Health (Add Health)
expected_update_frequency: yearly
tags: [health, longitudinal, adolescent-health, education]
api_config:
  url: https://addhealth.cpc.unc.edu/api/v1/data-releases
  method: GET
  headers:
    Accept: application/json
  expected_fields:
    - current_wave
    - last_updated
    - releases[0].wave
    - releases[0].release_date
    - releases[0].data_collection_year
    - releases[0].sample_size
    - releases[0].response_rate
    - releases[0].documentation_version
    - releases[0].data_files
  date_field: releases[0].release_date
