url: https://reporter.nih.gov/
name: NIH Research Portfolio Online Reporting Tools (RePORTER)
expected_update_frequency: weekly
tags: [nih, research, grants]
api_config:
  url: https://api.reporter.nih.gov/v2/projects/search
  method: POST
  headers:
    Accept: application/json
    Content-Type: application/json
  params:
    criteria:
      fiscal_years: [2024]
      limit: 1
      sort_field: "update_timestamp"
      sort_order: "desc"
  expected_fields:
    - meta.total
    - meta.offset
    - results[0].project_num
    - results[0].project_title
    - results[0].project_start_date
    - results[0].project_end_date
    - results[0].award_amount
    - results[0].award_notice_date
    - results[0].principal_investigators
    - results[0].organization
    - results[0].update_timestamp
  date_field: results[0].update_timestamp
