url: https://www.nhtsa.gov/laws-regulations/standing-general-order-crash-reporting#ads
name: Standing General Order 2021-01 | Incident Reporting for Automated Driving Systems
  and Level 2 Advanced Driver Assistance Systems
expected_update_frequency: null
tags:
  - transportation
