url: https://enforcedata.dol.gov/views/search.php
name: U.S. Department of Labor Enforcement Data
expected_update_frequency: null
tags:
  - labor
linked_urls:
  - url: https://docs.google.com/forms/d/e/1FAIpQLSeNQNpZIPvmYGO5eN9BkvHd5tthF2oCit0UAD4rFw_agB9u2g/viewform?usp=sf_link
    name: Customer Surveys
  - url: https://www.addthis.com/bookmark.php?v=250&username=xa-4b82cea50a7489e4
    name: [No text]
  - url: https://enforcedata.dol.gov/index.php?page=searchChooser
    name: SEARCH
  - url: https://enforcedata.dol.gov/index.php?page=data_catalogs
    name: DATA CATALOG
  - url: https://enforcedata.dol.gov/index.php?page=lab
    name: LABS
  - url: https://enforcedata.dol.gov/index.php?page=agency_tools
    name: AGENCY TOOLS
  - url: https://enforcedata.dol.gov/index.php?page=faq
    name: FAQ
  - url: https://enforcedata.dol.gov/index.php?page=whatsnew
    name: What's New
  - url: https://enforcedata.dol.gov/views/faqNaics.php
    name: link for hidden function
  - url: https://enforcedata.dol.gov/views/faqSic.php
    name: link for hidden function
  - url: https://enforcedata.dol.gov/views/search/search_infovis_whd_voa.php
    name: link for hidden function
  - url: https://enforcedata.dol.gov/views/search/search_infovis_ebsa_subjcode.php
    name: link for hidden function
  - url: https://www.dol.gov/general/foia
    name: Freedom of Information Act
  - url: https://www.dol.gov/general/privacynotice
    name: Privacy & Security Statement
  - url: https://www.dol.gov/general/disclaim
    name: Disclaimers
  - url: https://www.dol.gov/general/aboutdol/website-policies
    name: Important Website Notices
  - url: https://www.dol.gov/
    name: www.dol.gov
  - url: https://www.dol.gov/general/contact
    name: Contact Us
  - url: https://enforcedata.dol.gov/index.php?page=feedback
    name: FEEDBACK
