url: https://www.census.gov/programs-surveys/nsch.html
name: National Survey of Children's Health (NSCH)
expected_update_frequency: null
tags:
  - cb
linked_urls:
  - url: https://www.census.gov/en.html
    name: Census.gov
  - url: https://www.census.gov/topics.html
    name: Topics
  - url: https://www.census.gov/data
    name: Data & Maps
  - url: https://www.census.gov/programs-surveys.html
    name: Surveys & Programs
  - url: https://www.census.gov/library.html
    name: Resource Library
  - url: https://www.census.gov/data/data-tools/quickfacts.html
    name: QuickFacts U.S. Data Finder
  - url: https://data.census.gov/advanced
    name: Advanced Data Search
  - url: https://www.census.gov/idb
    name: International Database (IDB)
  - url: https://www.census.gov/programs-surveys/acs
    name: American Community Survey (ACS)
  - url: https://www.census.gov/about/history/census-records-family-history.html
    name: Census Records & Genealogy
  - url: https://www.census.gov/about/index.html
    name: Index A to Z
  - url: https://www.census.gov/topics/population/age-and-sex.html
    name: Age and Sex
  - url: https://www.census.gov/businessandeconomy
    name: Business and Economy
  - url: https://www.census.gov/topics/education.html
    name: Education
  - url: https://www.census.gov/disasters
    name: Emergency Management / Disasters
  - url: https://www.census.gov/topics/employment.html
    name: Employment
  - url: https://www.census.gov/topics/families.html
    name: Families and Living Arrangements
  - url: https://www.census.gov/geography
    name: Geography
  - url: https://www.census.gov/topics/health.html
    name: Health
  - url: https://www.census.gov/topics/population/hispanic-origin.html
    name: Hispanic Origin
  - url: https://www.census.gov/topics/housing.html
    name: Housing
  - url: https://www.census.gov/topics/income-poverty.html
    name: Income and Poverty
  - url: https://www.census.gov/topics/international-trade.html
    name: International Trade
  - url: https://www.census.gov/topics/population/migration.html
    name: Migration/Geographic Mobility
  - url: https://www.census.gov/topics/population.html
    name: Population
  - url: https://www.census.gov/topics/population/population-estimates.html
    name: Population Estimates
  - url: https://www.census.gov/govs
    name: Public Sector
  - url: https://www.census.gov/topics/population/race.html
    name: Race
  - url: https://www.census.gov/programs-surveys/decennial-census/about/rdo/summary-files.html
    name: Redistricting
  - url: https://www.census.gov/topics/public-sector/voting.html
    name: Voting and Registration
  - url: https://www.census.gov/data/data-tools/data-cedsci.html
    name: Explore data on data.census.gov
  - url: https://www.census.gov/academy
    name: Census Academy
  - url: https://www.census.gov/about/what/admin-data.html
    name: Combining Data
  - url: https://www.census.gov/data/data-tools.html
    name: Data Tools and Apps
  - url: https://www.census.gov/data/datasets.html
    name: Datasets
  - url: https://www.census.gov/developers/
    name: Developers
  - url: https://www.census.gov/data/experimental-data-products.html
    name: Experimental Data Products
  - url: https://www.census.gov/interactive-maps
    name: Interactive Maps
  - url: https://www.census.gov/geographies/mapping-files.html
    name: Mapping Files
  - url: https://www.census.gov/data/profile.html
    name: Profiles
  - url: https://www.census.gov/data/related-sites.html
    name: Related Sites
  - url: https://www.census.gov/data/software.html
    name: Software
  - url: https://www.census.gov/data/tables.html
    name: Tables
  - url: https://www.census.gov/data/training-workshops.html
    name: Training and Workshops
  - url: https://www.census.gov/library/visualizations.html
    name: Infographics and Visualizations
  - url: https://www.census.gov/2020census
    name: 2020 Census
  - url: https://www.census.gov/2026test
    name: 2026 Census Test
  - url: https://www.census.gov/2030census
    name: 2030 Census
  - url: https://www.census.gov/AHS
    name: American Housing Survey (AHS)
  - url: https://www.census.gov/abs
    name: Annual Business Survey (ABS)
  - url: https://www.census.gov/aies
    name: Annual Integrated Economic Survey (AIES)
  - url: https://www.census.gov/programs-surveys/cbp.html
    name: County Business Patterns (CBP)
  - url: https://www.census.gov/programs-surveys/cps.html
    name: Current Population Survey (CPS)
  - url: https://www.census.gov/EconomicCensus
    name: Economic Census
  - url: https://www.census.gov/householdpulse
    name: Household Pulse Survey
  - url: https://www.census.gov/internationalprograms
    name: International Programs
  - url: https://www.census.gov/programs-surveys/metro-micro.html
    name: Metro and Micro Areas
  - url: https://www.census.gov/popest
    name: Population Estimates
  - url: https://www.census.gov/programs-surveys/popproj.html
    name: Population Projections
  - url: https://www.census.gov/programs-surveys/saipe.html
    name: Small Area Income and Poverty
  - url: https://www.census.gov/programs-surveys/susb.html
    name: Statistics of U.S. Businesses
  - url: https://www.census.gov/sipp/
    name: Survey of Income and Program Participation (SIPP)
  - url: https://www.census.gov/data/data-tools/glossary.html
    name: Glossary
  - url: https://www.census.gov/AmericaCounts
    name: America Counts Stories
  - url: https://www.census.gov/library/audio.html
    name: Audio
  - url: https://www.census.gov/newsroom/blogs.html
    name: Blogs
  - url: https://www.census.gov/library/by-the-numbers.html
    name: By the Numbers
  - url: https://www.census.gov/newsroom/facts-for-features.html
    name: Facts for Features
  - url: https://www.census.gov/library/fact-sheets.html
    name: Fact Sheets
  - url: https://www.census.gov/library/photos.html
    name: Photos
  - url: https://www.census.gov/library/publications.html
    name: Publications
  - url: https://www.census.gov/library/spotlights.html
    name: Spotlights
  - url: https://www.census.gov/newsroom/stories.html
    name: Stats for Stories
  - url: https://www.census.gov/library/video.html
    name: Videos
  - url: https://www.census.gov/library/working-papers.html
    name: Working Papers
  - url: https://www.census.gov/programs-surveys/nsch/about.html
    name: About the National Survey of Children’s Health
  - url: https://www.census.gov/programs-surveys/nsch/data.html
    name: Data
  - url: https://www.census.gov/programs-surveys/nsch/information.html
    name: Information for Respondents
  - url: https://www.census.gov/programs-surveys/nsch/nschnewsandupdates.html
    name: News and Updates
  - url: https://www.census.gov/programs-surveys/nsch/technical-documentation.html
    name: Technical Documentation
  - url: https://www.hrsa.gov/index.html
    name: Sponsored By
  - url: https://www.mchb.hrsa.gov/
    name: Maternal and Child Health Bureau
  - url: https://www.census.gov/programs-surveys/nsch/data/datasets.2023.html
    name: 2023 NSCH Data ReleaseAccess the 2023 public use microdata files
  - url: https://www.census.gov/programs-surveys/nsch/technical-documentation/questionnaires.html
    name: NSCH QuestionnairesCopies of the NSCH screener and topical questionnaires.
  - url: https://www.census.gov/randomsamplings
    name: Random Samplings
  - url: https://www.census.gov/researchmatters
    name: Research Matters
  - url: https://www.census.gov/quality/
    name: Information Quality
  - url: https://www.census.gov/datalinkage
    name: Data Linkage Infrastructure
  - url: https://www.census.gov/privacy
    name: Data Protection and Privacy Policy