url: https://www.cdc.gov/nchs/nhcs/index.html
name: National Hospital Care Survey
expected_update_frequency: null
tags:
  - health
  - cdc
linked_urls:
  - url: https://www.cdc.gov
    name: CDC
  - url: https://www.cdc.gov/nchs/about/index.html
    name: National Center for Health Statistics
  - url: https://www.cdc.gov/nchs/nhcs/
    name: National Hospital Care Survey
  - url: https://www.cdc.gov/nchs/nhcs/data/index.html
    name: Questionnaires, Data Sets, and Documentation
  - url: https://www.cdc.gov/nchs/nhcs/results-publications/index.html
    name: Publications
  - url: https://www.cdc.gov/nchs/nhcs-participants/about/index.html
    name: NHCS Participants
  - url: https://www.cdc.gov/nchs/dhcs/index.htm
    name: National Health Care Surveys
  - url: https://www.cdc.gov/nchs/nhcs/site.html
    name: View All NHCS
  - url: https://www.cdc.gov/nchs/ndi/index.html
    name: National Death Index
  - url: https://www.cdc.gov/rdc/b1datatype/Dt1224h.htm
    name: National Center for Health Statistics Research Data Center
  - url: https://www.cdc.gov/rdc/application-process/submission.html
    name: Research Data Center Application
  - url: https://www.cdc.gov/nchs/nhcs/2020nhcs.htm
    name: File
  - url: https://www.cdc.gov/nchs/data/nhsr/nhsr201.pdf
    name: National Hospital Care Survey Demonstration Projects Examination of Maternal Health Outcomes by Housing Assistance Status
  - url: https://www.cdc.gov/nchs/data/series/sr_02/sr02-205.pdf
    name: Validation of the Enhanced Opioid Identification and Co-occurring Disorders Algorithms
  - url: https://www.cdc.gov/nchs/products/nchs_listservs.htm
    name: National Hospital Care Survey Data Listserv
  - url: https://www.cdc.gov/nchs/dhcs/
    name: National Health Care Surveys Program
  - url: https://www.cdc.gov/nchs/nhds/
    name: National Hospital Discharge Survey
  - url: https://archive.cdc.gov/
    name: CDC Archive
  - url: https://stacks.cdc.gov/
    name: Public Health Publications
  - url: https://hhs.gov
    name: HHS.gov
  - url: https://usa.gov
    name: USA.gov