url: https://wonder.cdc.gov/vaers.html
name: Vaccine Adverse Event Reporting System (VAERS)
expected_update_frequency: null
tags:
  - vaccine
  - health
  - cdc
linked_urls:
  - url: https://www.cdc.gov
    name: Centers for Disease Control and Prevention. CDC twenty four seven. Saving Lives, Protecting PeopleCenters for Disease Control and Prevention. CDC twenty four seven. Saving Lives, Protecting People
  - url: https://www.cdc.gov/az/
    name: A-Z Index
  - url: https://wonder.cdc.gov/
    name: CDC WONDER
  - url: https://wonder.cdc.gov/wonder/help/faq.html
    name: FAQs
  - url: https://wonder.cdc.gov/wonder/help/main.html
    name: Help
  - url: https://wonder.cdc.gov/controller/datarequest?stage=contactus&action=start
    name: Contact Us
  - url: https://wonder.cdc.gov/controller/datarequest?stage=search&action=current
    name: WONDER Search
  - url: https://wonder.cdc.gov/vaers.html
    name: TP Docs Home
    name: Syndicate
  - url: https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=https%3A%2F%2Fwww.cdc.gov%2Findex.htm&title=CDC%20Works%2024/7&description=As%20the%20nation%27s%20health%20protection%20agency,%20CDC%20saves%20lives%20and%20protects%20people%20from%20health,%20safety,%20and%20security%20threats.&via=CDCgov&ct=0&media=https://www.cdc.gov/homepage/images/centers-for-disease-control-and-prevention.png
    name: Facebook
  - url: https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=https%3A%2F%2Fwww.cdc.gov%2Findex.htm&title=CDC%20Works%2024/7&description=As%20the%20nation%27s%20health%20protection%20agency,%20CDC%20saves%20lives%20and%20protects%20people%20from%20health,%20safety,%20and%20security%20threats.&via=CDCgov&ct=0&media=https://www.cdc.gov/homepage/images/centers-for-disease-control-and-prevention.png
    name: Twitter
  - url: https://api.addthis.com/oexchange/0.8/forward/linkedin/offer?url=https%3A%2F%2Fwww.cdc.gov%2Findex.htm&title=CDC%20Works%2024/7&description=As%20the%20nation%27s%20health%20protection%20agency,%20CDC%20saves%20lives%20and%20protects%20people%20from%20health,%20safety,%20and%20security%20threats.&via=CDCgov&ct=0&media=https://www.cdc.gov/homepage/images/centers-for-disease-control-and-prevention.png
    name: LinkedIn
  - url: https://api.addthis.com/oexchange/0.8/forward/email/offer?url=https%3A%2F%2Fwww.cdc.gov%2Findex.htm&title=CDC%20Works%2024/7&description=As%20the%20nation%27s%20health%20protection%20agency,%20CDC%20saves%20lives%20and%20protects%20people%20from%20health,%20safety,%20and%20security%20threats.&via=CDCgov&ct=0&media=https://www.cdc.gov/homepage/images/centers-for-disease-control-and-prevention.png
    name: Email
  - url: https://wonder.cdc.gov/wonder/help/vaers.html
    name: Dataset Documentation
  - url: https://vaers.hhs.gov/data.html
    name: Other Data Access
  - url: https://wonder.cdc.gov/datause.html
    name: Data Use Restrictions
  - url: https://wonder.cdc.gov/wonder/help/quickstart.html
    name: How to Use WONDER
  - url: http://vaers.hhs.gov
    name: www.vaers.hhs.gov
  - url: https://www.cdc.gov/vaccinesafety/ensuringsafety/monitoring/vaers/access-VAERS-data.html
    name: How to Access VAERS Data through VAERS WONDER System page.
  - url: http://youtu.be/cOH7cFWS7o4?t=44s
    name: Section 1 Introduction to VAERS.
  - url: http://youtu.be/cOH7cFWS7o4?t=2m28s
    name: Section 2 How to Search VAERS Public Data.
  - url: http://youtu.be/cOH7cFWS7o4?t=10m37s
    name: Section 3 Strengths and Limitations of VAERS Data.
  - url: http://youtu.be/cOH7cFWS7o4?t=12m13s
    name: Section 4 Where to Get More Information.
  - url: https://www.cdc.gov/cdc-info/index.html
    name: Visit CDC-INFO
  - url: https://wwwn.cdc.gov/dcs/contactus/form
    name: Email CDC-INFO
  - url: https://www.cdc.gov/about/default.htm
    name: About CDC
  - url: https://jobs.cdc.gov
    name: Jobs
  - url: https://www.cdc.gov/funding
    name: Funding
  - url: https://www.cdc.gov/Other/policies.html
    name: Policies
  - url: https://www.cdc.gov/other/plugins/index.html
    name: File Viewers & Players
  - url: https://www.cdc.gov/od/foia
    name: FOIA
  - url: https://www.cdc.gov/eeo/nofearact/index.htm
    name: No Fear Act
  - url: https://oig.hhs.gov
    name: OIG
  - url: https://www.cdc.gov/other/nondiscrimination.html
    name: Nondiscrimination
  - url: https://www.cdc.gov/contact/accessibility.html
    name: Accessibility
  - url: https://www.hhs.gov/vulnerability-disclosure-policy/index.html
    name: Vulnerability Disclosure Policy
  - url: https://www.hhs.gov/es/vulnerability-disclosure-policy/index.html
    name: Español
  - url: https://www.cdc.gov/cdctv
    name: CDC TV
  - url: https://tools.cdc.gov/podcasts/rss.asp
    name: RSS
  - url: https://wwwn.cdc.gov/dcs/RequestForm.aspx
    name: Email
  - url: https://www.hhs.gov
    name: U.S. Department of Health & Human Services
  - url: https://www.usa.gov/
    name: USA.gov
  - url: https://www.cdc.gov/Other/disclaimer.html
    name: CDC Website Exit Disclaimer
  - url: https://cdc.112.2o7.net
    name: [No text]