url: https://wonder.cdc.gov/cancer.html
name: United States Cancer Statistics
expected_update_frequency: null
tags:
  - health
  - cdc
  - cancer
linked_urls:
  - url: https://www.cdc.gov
    name: Centers for Disease Control and Prevention. CDC twenty four seven. Saving Lives, Protecting PeopleCenters for Disease Control and Prevention. CDC twenty four seven. Saving Lives, Protecting People
  - url: https://www.cdc.gov/az/
    name: A-Z Index
  - url: https://wonder.cdc.gov/
    name: CDC WONDER
  - url: https://wonder.cdc.gov/wonder/help/faq.html
    name: FAQs
  - url: https://wonder.cdc.gov/controller/datarequest?stage=search&action=current
    name: WONDER Search
  - url: https://wonder.cdc.gov/cancer.html
    name: United States Cancer Statistics Public Information Data
  - url: https://wonder.cdc.gov/cancer-v2021.html
    name: United States and Puerto Rico Cancer Statistics, 1999-2021 Incidence Request
  - url: https://wonder.cdc.gov/wonder/help/cancer-v2021.html
    name: United States Cancer Statistics Public Information Data Incidence
  - url: https://wonder.cdc.gov/cancermort-v2021.html
    name: United States and Puerto Rico Cancer Statistics, 1999-2021 Mortality Request
  - url: https://wonder.cdc.gov/wonder/help/cancermort-v2021.html
    name: United States Cancer Statistics Public Information Mortality Data
  - url: https://wonder.cdc.gov/cancermir-v2021.html
    name: United States and Puerto Rico Cancer Statistics, 1999-2021 Mortality Incidence Rate Ratios Request
  - url: https://wonder.cdc.gov/wonder/help/cancermir-v2021.html
    name: United States Cancer Statistics Mortality Incidence Rate Ratios
  - url: https://gis.cdc.gov/Cancer/USCS/DataViz.html?ref=dGFiPXRhYlN1cnZpdmFsJnFzPTEwMw==
    name: United States Cancer Statistics Data Visualizations
  - url: https://wonder.cdc.gov/cancer-archives.html
    name: Archived Data
  - url: https://www.cdc.gov/uscs
    name: United States Cancer Statistics
  - url: https://www.cdc.gov/cancer/uscs/technical_notes/contributors/
    name: USCS Contributors
  - url: http://www.cdc.gov/cancer/npcr/
    name: National Program of Cancer Registries (NPCR)
  - url: http://seer.cancer.gov/about/
    name: Surveillance, Epidemiology and End Results (SEER)
  - url: http://www.cdc.gov/nchs/nvss/deaths.htm
    name: National Vital Statistics System (NVSS)
  - url: http://seer.cancer.gov/codrecode/
    name: SEER Cause of Death Recodes
  - url: https://www.cdc.gov/cdc-info/index.html
    name: CDC-INFO
  - url: https://www.cdc.gov/about/default.htm
    name: About CDC
  - url: https://www.cdc.gov/funding
    name: Funding
  - url: https://www.cdc.gov/cdctv
    name: CDC TV
  - url: https://tools.cdc.gov/podcasts/rss.asp
    name: RSS
  - url: https://www.hhs.gov
    name: U.S. Department of Health & Human Services
