url: https://www.nhats.org/researcher/nhats
name: National Health and Aging Trends Study (NHATS)
expected_update_frequency: null
tags:
  - health
  - aging
linked_urls:
  - url: https://www.nhats.org/researcher/nhats
    name: NHATS
  - url: https://www.nhats.org/researcher/nsoc
    name: National Study of Caregiving (NSOC)
  - url: https://www.nhats.org/researcher/data-access
    name: Data Access
  - url: https://www.nhats.org/publications/search
    name: Publications
  - url: https://micda.isr.umich.edu/research/nhats-trends-dashboards/
    name: Trends
  - url: https://www.nhats.org/researcher/about
    name: About
  - url: https://www.nhats.org/researcher/nhats/methods-documentation?id=user_guide
    name: User Guides
  - url: https://www.nhats.org/researcher/nhats/methods-documentation?id=data_collection
    name: Data Collection Materials
  - url: https://www.nhats.org/researcher/nhats/methods-documentation?id=technical-papers
    name: Technical Papers
  - url: https://www.nhats.org/researcher/nhats/methods-documentation?id=instruments
    name: Instruments
  - url: https://www.nhats.org/researcher/nhats/methods-documentation?id=variable-crosswalk
    name: Instrument-Variable Crosswalks
  - url: https://www.nhats.org/researcher/nhats/videos
    name: Getting Started
  - url: https://www.nhats.org/researcher/nsoc/methods-documentation?id=user_guide
    name: User Guide
  - url: https://www.nhats.org/researcher/nsoc/methods-documentation?id=variable-crosswalk
    name: CrossWalks
  - url: https://www.nhats.org/researcher/nsoc/methods-documentation?id=technical_papers
    name: Technical Papers
  - url: https://www.nhats.org/researcher/nsoc/methods-documentation?id=instruments
    name: Instruments
  - url: https://www.nhats.org/researcher/nsoc/videos
    name: Getting Started
  - url: https://www.nhats.org/researcher/data-access/public-use-files
    name: Public Use Files
  - url: https://www.nhats.org/researcher/data-access/sensitive-data-files?id=nsoc_other_sensitive_files
    name: Sensitive Files
  - url: https://www.nhats.org/researcher/data-access/sensitive-data-files?id=restricted_data_files
    name: Restricted Files
  - url: https://www.nhats.org/researcher/data-access/cross-year-search
    name: Cross Year Search
  - url: https://www.nhats.org/researcher/about?id=at-a-glance
    name: At-a-Glance
  - url: https://www.nhats.org/researcher/about?id=leadership
    name: Leadership
  - url: https://www.nhats.org/researcher/about?id=advisory-boards
    name: Advisory Board
  - url: https://www.nhats.org/researcher/about?id=sponsors
    name: Sponsors
  - url: https://mynhats.org/nhats
    name: NHATS Participants
  - url: https://mynhats.org/nsoc
    name: NSOC Participants
  - url: https://www.nhats.org/researcher
    name: Welcome Researchers
  - url: https://www.nhats.org/user/register
    name: Create new account
  - url: https://www.nhats.org/user/password
    name: Reset your password
  - url: https://www.jhsph.edu/
    name: [No text]
  - url: https://isr.umich.edu/
    name: [No text]
  - url: https://www.westat.com/
    name: [No text]
  - url: https://www.westat.com/privacy-policy
    name: Westat's Privacy Policy
  - url: https://www.adobe.com/acrobat/pdf-reader.html
    name: PDF Reader
  - url: https://mynhatsdemo.wesdemo.com/nhats
    name: NHATSParticipants
  - url: https://mynhatsdemo.wesdemo.com/nsoc
    name: NSOCParticipants