url: https://addhealth.cpc.unc.edu/
name: National Longitudinal Study of Adolescent to Adult Health (Add Health)
expected_update_frequency: null
tags:
  - health
linked_urls:
  - url: https://addhealth.cpc.unc.edu/
    name: Add Health
  - url: https://addhealth.cpc.unc.edu/about/
    name: About
  - url: https://addhealth.cpc.unc.edu/about/contact-us/
    name: Contact Us
  - url: https://addhealth.cpc.unc.edu/documentation/
    name: Documentation
  - url: https://addhealth.cpc.unc.edu/documentation/study-design/
    name: Study Design
  - url: https://addhealth.cpc.unc.edu/documentation/user-guides/
    name: User Guides
  - url: https://addhealth.cpc.unc.edu/documentation/codebooks/
    name: Codebooks
  - url: https://addhealth-navigator.cpc.unc.edu/
    name: Add Health Navigator
  - url: https://addhealth.cpc.unc.edu/documentation/codebook-explorer/
    name: Codebook Explorer
  - url: https://addhealth.cpc.unc.edu/documentation/add-health-contextual-variable-inventory/
    name: Contextual Variable Inventory
  - url: https://addhealth.cpc.unc.edu/documentation/restricted-use-datasets-index/
    name: Restricted-Use Datasets Index
  - url: https://addhealth.cpc.unc.edu/documentation/frequently-asked-questions/
    name: Frequently Asked Questions
  - url: https://addhealth.cpc.unc.edu/data/
    name: Data
  - url: https://addhealth.cpc.unc.edu/data/ancillary-studies/
    name: Ancillary Studies
  - url: https://addhealth.cpc.unc.edu/ah-events/
    name: Events
  - url: https://addhealth.cpc.unc.edu/participants/
    name: Participants
  - url: https://addhealth.cpc.unc.edu/home/
    name: Home Page
  - url: https://addhealth.cpc.unc.edu/featured-page-2/
    name: Home Page
  - url: https://addhealth.cpc.unc.edu/user-guides/
    name: User Guides
  - url: https://addhealth.cpc.unc.edu/codebooks/
    name: Codebooks
  - url: https://addhealth.cpc.unc.edu/contact-us
    name: Contact us
  - url: https://addhealth.cpc.unc.edu/data/ancillary-studies
    name: Ancillary Studies
  - url: https://addhealth.cpc.unc.edu/participants
    name: Participants
  - url: https://addhealth.cpc.unc.edu/frequently-asked-questions/
    name: FAQs
  - url: https://www.unc.edu/about/privacy-statement/
    name: Privacy Policy
  - url: https://addhealth.cpc.unc.edu/accessibility/
    name: Accessibility
  - url: https://addhealth.cpc.unc.edu/email-signup
    name: Sign up for emails