url: https://archive.cdc.gov/www_cdc_gov/nchs/nhis/sexual_orientation/references.htm
name: CDC NCHS NHIS Sexual Orientation References
expected_update_frequency: null
tags:
  - cdc
  - sogi
archived_content:
