url: https://www.cdc.gov/nchs/webinars/sexual-orientation-gender-identity-measures.html
name: Sexual Orientation and Gender Identity Measures in NCHS Data Systems
expected_update_frequency:
tags:
  - cdc
  - sogi
archived_content:
  - url: https://web.archive.org/web/20250127094426/https://www.cdc.gov/nchs/webinars/sexual-orientation-gender-identity-measures.html
    name: Sexual Orientation and Gender Identity Measures in NCHS Data Systems
