url: https://grants.nih.gov/grants/guide/notice-files/NOT-OD-20-031.html
name: Notice of NIH's Interest in Diversity
expected_update_frequency: null
tags:
  - nih
  - diversity
archived_content:
  - url: https://web.archive.org/web/20250116021719/https://grants.nih.gov/grants/guide/notice-files/NOT-OD-20-031.html
    name: NIH Grants Notice - SOGI Data Collection