url: https://www.cdc.gov/nchs/data/bsc/bscpres_dahlhamer_oct2014.pdf
name: Sexual Orientation Results from the National Health Interview Survey
expected_update_frequency: null
tags:
  - cdc
  - sogi
archived_content:
  - https://web.archive.org/web/20241130094850/https://www.cdc.gov/nchs/data/bsc/bscpres_dahlhamer_oct2014.pdf
