url: https://www.cancer.gov
name: Cancer.gov
expected_update_frequency: null
tags:
  - cdc
  - cancer
archived_content:
  - url: https://web.archive.org/web/20250124100301/https://www.cancer.gov/about-cancer/understanding/disparities
    name: Health Disparities Page
  - url: https://web.archive.org/web/20231001012308/https://www.cancer.gov/about-nci/organization/crchd/about-health-disparities/resources/cancer-moonshot-scholars-fact-sheet
    name: Cancer Moonshot Scholars Fact Sheet
  - url: https://web.archive.org/web/20250126061519/https://deainfo.nci.nih.gov/advisory/joint/1224/Bailey.pdf
    name: Cancer Moonshot Scholars - Bailey Report
linked_urls:
  - url: https://www.cancer.gov/about-cancer/understanding/disparities
    name: Cancer Health Disparities
    type: html
  - url: https://www.cancer.gov/about-nci/organization/crchd/about-health-disparities/resources/cancer-moonshot-scholars-fact-sheet
    name: Cancer Moonshot Scholars Fact Sheet
    type: html
  - url: https://deainfo.nci.nih.gov/advisory/joint/1224/Bailey.pdf
    name: Cancer Moonshot Scholars - Bailey Report
    type: pdf
    
