url: https://www.cancer.gov
name: Cancer.gov
expected_update_frequency: null
tags:
  - cdc
  - cancer
archived_content:
  - url: https://web.archive.org/web/20250124100301/https://www.cancer.gov/about-cancer/understanding/disparities
    name: Health Disparities Page
  - url: https://web.archive.org/web/20231001012308/https://www.cancer.gov/about-nci/organization/crchd/about-health-disparities/resources/cancer-moonshot-scholars-fact-sheet
    name: Cancer Moonshot Scholars Fact Sheet
  - url: https://web.archive.org/web/20250126061519/https://deainfo.nci.nih.gov/advisory/joint/1224/Bailey.pdf
    name: Cancer Moonshot Scholars - Bailey Report
linked_urls:
  - url: https://www.cancer.gov/about-cancer/understanding/disparities
    name: Cancer Health Disparities
    type: html
  - url: https://www.cancer.gov/about-nci/organization/crchd/about-health-disparities/resources/cancer-moonshot-scholars-fact-sheet
    name: Cancer Moonshot Scholars Fact Sheet
    type: html
  - url: https://deainfo.nci.nih.gov/advisory/joint/1224/Bailey.pdf
    name: Cancer Moonshot Scholars - Bailey Report
    type: pdf
  - url: https://www.cancer.gov/
    name: National Cancer Institute
  - url: https://www.cancer.gov/about-cancer
    name: About Cancer
  - url: https://www.cancer.gov/types
    name: Cancer Types
  - url: https://www.cancer.gov/research
    name: Research
  - url: https://www.cancer.gov/grants-training
    name: Grants & Training
  - url: https://www.cancer.gov/news-events
    name: News & Events
  - url: https://www.cancer.gov/about-nci
    name: About NCI
  - url: https://www.cancer.gov/about-cancer/treatment
    name: Treatment
  - url: https://www.cancer.gov/about-cancer/treatment/side-effects
    name: Side Effects
  - url: https://www.cancer.gov/about-cancer/causes-prevention
    name: Causes & Prevention
  - url: https://www.cancer.gov/about-cancer/diagnosis-staging
    name: Diagnosis & Staging
  - url: https://www.cancer.gov/research/participate/clinical-trials-search
    name: Find a Clinical Trial
  - url: https://www.cancer.gov/grants-training/grants-funding/funding-opportunities
    name: Funding Opportunities
  - url: https://www.cancer.gov/research/resources
    name: Resources for Researchers
  - url: https://www.cancer.gov/grants-training/apply-grant
    name: Apply for a Grant
  - url: https://www.cancer.gov/grants-training/training/at-nci
    name: Training at NCI
  - url: https://www.cancer.gov/grants-training/grants-funding/contacts
    name: Find a Research Contact
  - url: https://www.cancer.gov/research/key-initiatives
    name: Key NCI Initiatives
  - url: https://www.cancer.gov/contact/emergency-preparedness
    name: Emergency ResourcesLearn about resources for patients and health care providers to continue cancer care when natural or human-made disasters occur.
  - url: https://www.cancer.gov/news-events/cancer-currents-blog/2025/lung-cancer-stigma-teaching-empathy
    name: Training Program Aims to Reduce Lung Cancer StigmaThe training program for health professionals is being tested in a clinical trial.
  - url: https://www.cancer.gov/news-events/cancer-currents-blog/2025/fructose-tumor-growth-liver-lipids
    name: How One Type of Sugar Might Help Tumors GrowFructose gets a lift from the liver to fuel the growth of some types of tumors, a new study suggests.
  - url: https://nationalcancerplan.cancer.gov/goals/maximize-data-utility
    name: Learn More
  - url: https://www.cancer.gov/research/leading-progress?cid=wl_cgov_hpfc_ap-rollout
    name: Learn More
  - url: https://www.cancer.gov/contact
    name: Contact Us
  - url: https://www.cancer.gov/about-nci/leadership
    name: Senior LeadersInformation about NCI senior leadership.
  - url: https://www.cancer.gov/about-nci/organization
    name: NCI Divisions, Offices, and CentersNCI has 30 divisions, offices, and centers who work together to build, maintain, and enhance a cohesive and comprehensive cancer research agenda.
  - url: https://www.cancer.gov/about-nci/advisory-boards
    name: Advisory Boards and Review GroupsNCI relies on advisory committees to provide advice on the National Cancer Program, NCI scientific priorities, and more.
  - url: https://www.cancer.gov/about-website
    name: About This Website
  - url: https://www.cancer.gov/policies/copyright-reuse
    name: Reuse & Copyright
  - url: https://www.cancer.gov/social-media
    name: Social Media
  - url: https://www.cancer.gov/publications
    name: Publications
  - url: https://www.cancer.gov/publications/dictionaries/cancer-terms
    name: Dictionary of Cancer Terms
  - url: https://www.cancer.gov/policies/accessibility
    name: Accessibility
  - url: https://www.cancer.gov/policies/foia
    name: FOIA
  - url: https://www.cancer.gov/policies/privacy-security
    name: Privacy & Security
  - url: https://www.cancer.gov/policies/disclaimer
    name: Disclaimers
  - url: https://www.hhs.gov/vulnerability-disclosure-policy/index.html
    name: Vulnerability Disclosure
  - url: https://livehelp.cancer.gov/
    name: Live Chat
  - url: https://nci.az1.qualtrics.com/jfe/form/SV_aeLLobt6ZeGVn5I
    name: Site Feedback
  - url: https://www.hhs.gov/
    name: U.S. Department of Health and Human Services
  - url: https://www.nih.gov/
    name: National Institutes of Health
  - url: https://usa.gov/
    name: USA.gov