url: https://www.cdc.gov/yrbs/media/pdf/2023/2023_analyze_sexual_minority_data.pdf
name: How to Analyze YRBS Sexual Minority Data
expected_update_frequency: null
tags:
  - cdc
  - sogi
  - youth
archived_content:
  - url: https://web.archive.org/web/20250124100301/https://www.cdc.gov/nchs/data/series/sr_02/sr02-191.pdf
    name: Sexual Minority Analysis Report
