url: https://www.cdc.gov/yrbs/media/pdf/2023/2023_analyze_sexual_minority_data.pdf
name: How to YRBS Analyze Sexual Minority Data
expected_update_frequency: null
tags:
  - cdc
  - sogi
  - youth
archived_content:
  - https://web.archive.org/web/20250109182259/https://www.cdc.gov/yrbs/media/pdf/2023/2023_Analyze_sexual_minority_data.pdf
