url: https://childreninadversity.gov
name: Advancing Protection and Care for Children in Adversity
expected_update_frequency: null
tags:
  - interagency
  - youth
archived_content:
  - url: https://web.archive.org/web/20250117222341/https://www.childreninadversity.gov/
    name: Advancing Protection and Care for Children in Adversity
    