url: https://neglecteddiseases.gov
name: USAID Neglected Tropical Diseases Program
expected_update_frequency: null
tags:
  - usaid
  - health
archived_content:
  - url: https://web.archive.org/web/20250122000632/https://www.neglecteddiseases.gov/
    name: USAID Neglected Tropical Diseases Program
