url: https://bjs.ojp.gov/data-collection/ncvs
name: National Crime Victimization Survey
description: The National Crime Victimization Survey (NCVS) is the nation's primary source of information on criminal victimization. Each year, data are obtained from a nationally representative sample of about 240,000 persons in about 150,000 households. Persons are interviewed on the frequency, characteristics, and consequences of criminal victimization in the United States.
omb_control_number: 1121-0111
