url: https://fpi.omb.gov/search
name: Federal Program Inventory
description: The Federal Program Inventory (FPI) is a searchable, publicly available tool created by the Office of Management and Budget (OMB) that provides information about federal programs, including their objectives, eligibility, and spending, to increase transparency and accessibility of federal spending. The FPI pulls data from existing government sources like SAM.gov and USASpending.gov.
