url: https://www.nass.usda.gov/AgCensus/
name: Census of Agriculture
description: The Census of Agriculture, conducted once every five years, looks at land use and ownership, producer characteristics, production practices, income, and expenditures. The Census of Agriculture is a complete count of U.S. farms and ranches and the people who operate them. Even small plots of land – whether rural or urban – count if $1,000 or more of agricultural products were produced and sold, or normally would have been sold, during the census year.
omb_control_number: 0535-0226
linked_urls:
  - url: https://www.nass.usda.gov/Publications/AgCensus/2022/index.php
    name: Reports and Publications
  - url: https://quickstats.nass.usda.gov/
    name: Quick Stats
  - url: https://quickstats.nass.usda.gov/api
    name: Quick Stats API
