url: https://usda.library.cornell.edu/concern/publications/5t34sj58c
name: Peanut Prices
description: This report is published weekly on Friday and includes the U.S. average price and marketings by type of peanut (Runner, Spanish, Valencia, and Virginia). The report also highlights averages and changes in peanut pricing for the week for farmer stock peanuts and runner-type peanuts. Data for this report is obtained from the first buyers of farmer stock peanuts.
omb_control_number: 0535-0003
