url: https://www.usaspending.gov/
name: USAspending
description: USAspending.gov is the official source for spending data for the U.S. Government. Its mission is to show the American public what the federal government spends every year and how it spends the money. You can follow the money from the Congressional appropriations to the federal agencies and down to local communities and businesses.
tags:
  - Economics
  - Federal Government
linked_urls:
  - url: https://www.usaspending.gov/data-sources
    name: Data Sources
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/data/data-sources-download.pdf
    name: Data Sources (pdf)
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/training-videos
    name: Training Videos
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/data/about-the-data-download.pdf
    name: About the Data (pdf)
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/data-dictionary
    name: Data Dictionary
    resource_type: Supporting Documentation Page
  - url: https://files.usaspending.gov/docs/Data_Dictionary_Crosswalk.xlsx
    name: Data Dictionary (xlsx)
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/submission-statistics?tab=submissions&fy=2025&period=5
    name: About These Statistics
    resource_type: Supporting Documentation Page
  - url: https://api.usaspending.gov/
    name: API Endpoints
    resource_type: API Endpoint
  - url: https://github.com/fedspendingtransparency/usaspending-website/tree/master
    name: USAspending GitHub
    resource_type:
  - url: https://github.com/fedspendingtransparency/usaspending-website/wiki
    name: Release Notes of the Latest Changes
    resource_type: Supporting Documentation Page
  - url: https://files.usaspending.gov/docs/USAspending-data-catalog.json
    name: Dataset Metadata (JSON)
    resource_type: Data File (JSON)
  - url: https://onevoicecrm.my.site.com/usaspending/s/database-download
    name: Database Download
    resource_type: Data Repository or Listings page
  - url: https://files.usaspending.gov/database_download/usaspending-db-setup.pdf
    name: Database Archive - Recommended Download and Restoration Proces (pdf)
    resource_type: Supporting Documentation Page
  - url: https://files.usaspending.gov/docs/Custom+Account+Data+Dictionary.xlsx
    name: Custom Account Data Dictionary
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/search
    name: Search Award Data
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/explorer/budget_function
    name: Explore Spending by Budget Function
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/explorer/agency
    name: Explore Spending by Agency
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/explorer/object_class
    name: Explore Spending by Object Class
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/agency
    name: Agency Profiles
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/federal_account
    name: Federal Account Profiles
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/state
    name: State and Territory Profiles
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/recipient
    name: Recipient Profiles
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/disaster/covid-19
    name: COVID-19 Spending
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/federal-spending-guide
    name: Federal Spending Guide
    resource_type: Supporting Documentation Page
  - url: https://www.usaspending.gov/download_center/award_data_archive
    name: Award Data Archive
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://files.usaspending.gov/award_data_archive/FY(All)_All_Contracts_Delta_20250324.zip
    name: Award Data - All Contracts Delta File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY(All)_All_Assistance_Delta_20250324.zip
    name: Award Data - All Financial Assistance Delta File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2025_All_Contracts_Full_20250324.zip
    name: FY25 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2025_All_Assistance_Full_20250324.zip
    name: FY25 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2024_All_Contracts_Full_20250324.zip
    name: FY24 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2024_All_Assistance_Full_20250324.zip
    name: FY24 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2023_All_Contracts_Full_20250324.zip
    name: FY23 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2023_All_Assistance_Full_20250324.zip
    name: FY23 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2022_All_Contracts_Full_20250324.zip
    name: FY22 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2022_All_Assistance_Full_20250324.zip
    name: FY22 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2021_All_Contracts_Full_20250324.zip
    name: FY21 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2021_All_Assistance_Full_20250324.zip
    name: FY21 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2020_All_Contracts_Full_20250324.zip
    name: FY20 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2020_All_Assistance_Full_20250324.zip
    name: FY20 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2019_All_Contracts_Full_20250324.zip
    name: FY19 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2019_All_Assistance_Full_20250324.zip
    name: FY19 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2018_All_Contracts_Full_20250324.zip
    name: FY18 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2018_All_Assistance_Full_20250324.zip
    name: FY18 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2017_All_Contracts_Full_20250324.zip
    name: FY17 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2017_All_Assistance_Full_20250324.zip
    name: FY17 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2016_All_Contracts_Full_20250324.zip
    name: FY16 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2016_All_Assistance_Full_20250324.zip
    name: FY16 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2015_All_Contracts_Full_20250324.zip
    name: FY15 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2015_All_Assistance_Full_20250324.zip
    name: FY15 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2014_All_Contracts_Full_20250324.zip
    name: FY14 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2014_All_Assistance_Full_20250324.zip
    name: FY14 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2013_All_Contracts_Full_20250324.zip
    name: FY13 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2013_All_Assistance_Full_20250324.zip
    name: FY13 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2012_All_Contracts_Full_20250324.zip
    name: FY12 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2012_All_Assistance_Full_20250324.zip
    name: FY12 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2011_All_Contracts_Full_20250324.zip
    name: FY11 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2011_All_Assistance_Full_20250324.zip
    name: FY11 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2010_All_Contracts_Full_20250324.zip
    name: FY10 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2010_All_Assistance_Full_20250324.zip
    name: FY10 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2009_All_Contracts_Full_20250324.zip
    name: FY09 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2009_All_Assistance_Full_20250324.zip
    name: FY09 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2008_All_Contracts_Full_20250324.zip
    name: FY08 Award Data - All Contracts Full File
    resource_type: Data File (Other)
  - url: https://files.usaspending.gov/award_data_archive/FY2008_All_Assistance_Full_20250324.zip
    name: FY08 Award Data - All Financial Assistance Full File
    resource_type: Data File (Other)
  - url: https://www.usaspending.gov/download_center/custom_award_data
    name: Custom Award Data
    resource_type: Interactive Dashboard/Data Explorer
  - url: https://www.usaspending.gov/download_center/custom_account_data
    name: Custom Account Data
    resource_type: Interactive Dashboard/Data Explorer
