url: https://www.opm.gov/fevs/
name: OPM FEVS
description: The Office of Personnel Management Federal Employee Viewpoint Survey (OPM FEVS) is an organizational climate survey and assesses how employees jointly experience the policies, practices, and procedures characteristic of their agency and its leadership. Results from the OPM FEVS offers insights into whether, and to what extent, workplace conditions characterizing successful organizations are present in Federal agencies, information important to successful organizational change and development initiatives.
omb_control_number: 3206-0252
linked_urls:
  - url: https://www.opm.gov/fevs/public-data-file/
    name: Public Data File
  - url: https://www.opm.gov/fevs/reports/opm-fevs-dashboard/
    name: Dashboard
