url: https://www.fedscope.opm.gov/
name: FedScope
description: The Office of Personnel Management is the focal point for providing statistical information about the Federal civilian workforce. To satisfy customer's need for workforce data, FedScope was launched in the fall of 2000. This online tool allows customers to access and analyze the most popular data elements from OPM's Enterprise Human Resources Integration-Statistical Data Mart (EHRI-SDM). Customers include Federal government agencies, researchers, the media, and the general public.
linked_urls:
  - url: https://www.opm.gov/data/datasets/Index.aspx?tag=FedScope
    name: Raw Datasets
  - url: https://www.fedscope.opm.gov/datadefn/index.asp
    name: Data Definitions
